import { AlignmentType, BorderStyle, Document, ExternalHyperlink, Footer, Header, HeadingLevel, ImageRun, PageBreak, PageNumber, Paragraph, Packer, ShadingType, Table, TableCell, TableOfContents, TableRow, TextRun, WidthType } from 'docx'
import { DOCX_COLORS } from '../publishing/design-tokens.js'

let imageLoader = async source => new Uint8Array(await (await fetch(source)).arrayBuffer())
export function setImageLoader(loader) { imageLoader = loader }
const colors = DOCX_COLORS
const borders = { top:{style:BorderStyle.SINGLE,size:2,color:colors.line}, bottom:{style:BorderStyle.SINGLE,size:2,color:colors.line}, left:{style:BorderStyle.SINGLE,size:2,color:colors.line}, right:{style:BorderStyle.SINGLE,size:2,color:colors.line} }
function rich(text='', opts={}) { return text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g).filter(Boolean).map(part => part.startsWith('**') ? new TextRun({...opts,text:part.slice(2,-2),bold:true}) : part.startsWith('`') ? new TextRun({...opts,text:part.slice(1,-1),font:'Consolas',color:colors.indigo,shading:{type:ShadingType.CLEAR,fill:'EEF1FA'}}) : new TextRun({...opts,text:part})) }
const p = (text='', options={}) => new Paragraph({ spacing:{after:120,line:300}, ...options, children:Array.isArray(text)?text:rich(text) })
const h = (text, level=HeadingLevel.HEADING_2) => new Paragraph({ heading:level, keepNext:true, spacing:{before:240,after:100}, children:[new TextRun({text,bold:true,color:colors.indigo})] })
const tableBox = (title, children, fill='F7F9FC') => new Table({ width:{size:100,type:WidthType.PERCENTAGE}, rows:[new TableRow({children:[new TableCell({borders,shading:{type:ShadingType.CLEAR,fill},margins:{top:130,bottom:130,left:160,right:160},children:[p([new TextRun({text:title,bold:true,color:colors.navy})]),...children]})]})] })
function code(lines, filename) { return [p([new TextRun({text:filename,bold:true,font:'Consolas',color:colors.indigo})]), ...lines.map((line,i)=>p([new TextRun({text:`${String(i+1).padStart(2,' ')}  ${line || ' '}`,font:'Consolas',size:19})],{shading:{type:ShadingType.CLEAR,fill:'F4F6F9'},spacing:{after:0,line:260},keepLines:true}))] }
function list(items, numbering='bullet') { return items.map(item=>p(rich(item),{numbering:{reference:numbering,level:0}})) }
function bytecodeMapToDocx(b) {
  const content = []
  for (const [groupIndex, group] of b.groups.entries()) {
    content.push(p([new TextRun({text:`SOURCE ${groupIndex+1}: `,bold:true,color:colors.indigo}),new TextRun({text:group.source,font:'Consolas',bold:true})]))
    for (const [actionIndex, action] of group.actions.entries()) {
      content.push(p([new TextRun({text:`${actionIndex+1}. ${action.opcode}: `,bold:true,color:colors.teal}),...rich(action.action)]))
      if (action.state) content.push(p([new TextRun({text:'State: ',bold:true}),...rich(action.state)]))
    }
  }
  if (b.command) content.push(p([new TextRun({text:'Try it: ',bold:true}),new TextRun({text:b.command,font:'Consolas'})]))
  if (b.caption) content.push(p([new TextRun({text:b.caption,italics:true,color:'596579'})]))
  return [tableBox(b.version||'BYTECODE MAP',content,'EEF1FA')]
}
async function blockToDocx(b) {
  switch(b.type) {
    case 'heading': return [h(b.text)]
    case 'paragraph': return [p(b.text)]
    case 'image': { const data=await imageLoader(b.src, b); const width=560; return [new Paragraph({alignment:AlignmentType.CENTER,children:[new ImageRun({data,type:b.file?.toLowerCase().endsWith('.png')?'png':'jpg',transformation:{width,height:Math.round(width*b.h/b.w)},altText:{title:b.alt,description:b.alt,name:b.alt}})]}),...(b.caption?[p([new TextRun({text:b.caption,italics:true,color:'5B6575',size:19})],{alignment:AlignmentType.CENTER})]:[]),...(b.points||[]).map((point,index)=>p([new TextRun({text:`${index+1}  `,bold:true,color:colors.indigo}),...rich(point)]))] }
    case 'arc-start': return [tableBox(`LEARNING ARC · ${b.arcTitle}`,[p([new TextRun({text:b.title,bold:true,color:colors.navy}),new TextRun({text:`  Step ${b.step} of ${b.total}`,italics:true,color:'596579'})]),p(rich(b.text)),p([new TextRun({text:`${b.weKnowLabel || 'Starting tools'}: `,bold:true}),...rich(b.weKnow.join(' • '))]),p([new TextRun({text:`${b.weNeedLabel || 'What this arc will unlock'}: `,bold:true}),...rich(b.weNeed.join(' • '))])],'EEF5FA')]
    case 'arc-progress': return [tableBox(`${b.arcTitle} · STEP ${b.step} OF ${b.total}`,[p([new TextRun({text:`Now: ${b.currentFocus}. `,bold:true,color:colors.indigo}),...rich(b.text)])],'F3F6FA')]
    case 'mission': return [tableBox(`${b.label || 'OUR MISSION'} · ${b.title}`,[p(rich(b.text)),p([new TextRun({text:`${b.weKnowLabel || 'What we know'}: `,bold:true}),...rich(b.weKnow.join(' • '))]),p([new TextRun({text:`${b.weNeedLabel || 'What we need'}: `,bold:true}),...rich(b.weNeed.join(' • '))])],'EEF5FA')]
    case 'think': return [tableBox('PAUSE & THINK',[p(b.prompt),p([new TextRun({text:'Answer: ',bold:true}),...rich(b.answer)])],'FFF8E8')]
    case 'guess': return [tableBox('MAKE A GUESS',[p(b.prompt),...(b.code?code(b.code.split('\n'),'prediction.py'):[]),...list(b.options.map((x,i)=>`${String.fromCharCode(65+i)}. ${x}`)),p([new TextRun({text:`Answer: ${b.options[b.answerIndex]}. `,bold:true}),...rich(b.explain)])],'F3F0FA')]
    case 'bug': return [tableBox('BUG HUNT',[p(b.prompt),...code(b.lines,'bug_hunt.py'),p([new TextRun({text:`Answer: line ${b.bugLine}. `,bold:true}),...rich(b.explain)])],'FFF4E8')]
    case 'callout': return [tableBox(b.title || 'Note',b.paragraphs.map(x=>p(x)),b.variant==='analogy'?'EEF8F6':'F2F4FA')]
    case 'flow': { const stages=b.stages||[{eyebrow:'INPUT',title:b.input[0],detail:b.input[1]},{eyebrow:'PROCESS',title:b.process[0],detail:b.process[1]},{eyebrow:'OUTPUT',title:b.output[0],detail:b.output[1]}]; return [h(b.title||'Input → Process → Output'),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:stages.map((stage,index)=>new TableRow({children:[new TableCell({borders,width:{size:12,type:WidthType.PERCENTAGE},shading:{type:ShadingType.CLEAR,fill:'EEF1FA'},children:[p([new TextRun({text:String(index+1),bold:true,color:colors.indigo})])]}),new TableCell({borders,shading:{type:ShadingType.CLEAR,fill:'F5F7FB'},children:[p([new TextRun({text:stage.eyebrow||`STEP ${index+1}`,bold:true,color:colors.indigo,size:18})]),p([new TextRun({text:stage.title,bold:true,color:colors.navy}),]),p(stage.detail)]})]}))}),...(b.caption?[p([new TextRun({text:b.caption,italics:true,color:'596579',size:19})],{alignment:AlignmentType.CENTER})]:[])] }
    case 'bytecode-map': return bytecodeMapToDocx(b)
    case 'blueprint': return [...(b.showHeading===false?[]:[h('Plan before we type')]),tableBox('PROGRAM BLUEPRINT',[p(`Purpose: ${b.purpose}`),p(`Input: ${b.input}`),p(`Processing: ${b.processing}`),p(`Output: ${b.output}`),p(`Files: ${b.files.join(', ') || 'None'}`)])]
    case 'code': return [...(b.showHeading===false?[]:[h('The code')]),...code(b.lines,b.filename)]
    case 'runviz': return [...(b.showHeading===false?[]:[h('Program run: every step')]),...code(b.codeLines,b.filename),...b.steps.flatMap((s,i)=>[p([new TextRun({text:`${i+1}. ${s.title}`,bold:true,color:colors.indigo}),...(s.line?[new TextRun({text:` (line ${s.line})`,italics:true})]:[])]),p(s.explain),...(s.vars?.length?[p(`Memory: ${s.vars.map(v=>`${v.name} = ${v.value}`).join(', ')}`)]:[]),...(s.console?.length?[p(`Console: ${s.console.join(' | ')}`)]:[])])]
    case 'terminal': return [h('Expected output'),...code([`$ ${b.command}`,...b.lines],'Terminal')]
    case 'pipeline': return [h('Compare the routes'),...b.tracks.flatMap(t=>[h(`${t.icon} ${t.label}`,HeadingLevel.HEADING_3),...(t.summary?[p([new TextRun({text:t.summary,italics:true,color:'596579'})])]:[]),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:t.stages.map((s,i)=>new TableRow({children:[new TableCell({borders,width:{size:12,type:WidthType.PERCENTAGE},shading:{type:ShadingType.CLEAR,fill:'EEF1FA'},children:[p([new TextRun({text:`${i+1}`,bold:true,color:colors.indigo})]),p(s.icon)]}),new TableCell({borders,children:[p([new TextRun({text:s.name,bold:true,color:colors.navy})]),p([new TextRun({text:'What we have now: ',bold:true}),new TextRun({text:s.artifact,font:'Consolas',color:colors.indigo})]),p(s.description),...(s.example?[p([new TextRun({text:s.example,font:'Consolas',size:18,color:colors.text})],{shading:{type:ShadingType.CLEAR,fill:'F4F6F9'}})]:[])]})]}))})])]
    case 'steps': return [...(b.showHeading===false?[]:[h(b.title||'Try it yourself')]),...list(b.items,'steps')]
    case 'mistakes': return [h('Common mistakes and fixes'),...b.items.map(([bad,why])=>tableBox(`✗ ${bad}`,[p(why)],'FFF7E8'))]
    case 'quiz': return [h('Check your understanding'),...b.items.flatMap(([q,a],i)=>[p([new TextRun({text:`${i+1}. ${q}`,bold:true})]),p([new TextRun({text:'Answer: ',bold:true,color:colors.teal}),...rich(a)])])]
    case 'takeaways': return [h('Key takeaways'),tableBox('REMEMBER',list(b.items),'EEF7F4')]
    case 'aha': return [tableBox('THE AHA MOMENT',[p([new TextRun({text:b.text,bold:true,color:colors.teal})])],'EAF8F4')]
    case 'cliffhanger': return [tableBox(`NEXT DISCOVERY · ${b.title}`,[p(b.text)],'EEF1FA')]
    case 'resources': return [h('Keep exploring'),...b.items.map(([label,url])=>new Paragraph({children:[new ExternalHyperlink({link:url,children:[new TextRun({text:label,style:'Hyperlink'})]}),new TextRun({text:`: ${url}`,color:'657084',size:18})]}))]
    case 'definition': return [tableBox(`DEFINITION · ${b.term}`,[p(b.text),...(b.example?[p([new TextRun({text:'Example: ',bold:true}),...rich(b.example)])]:[])],'EEF1FA')]
    case 'worked-example': return [tableBox(`WORKED EXAMPLE · ${b.title}`,[p([new TextRun({text:'Problem: ',bold:true}),...rich(b.problem)]),...list(b.steps,'steps'),p([new TextRun({text:'Result: ',bold:true,color:colors.teal}),...rich(b.result)])],'F3F6FA')]
    case 'case-study': return [tableBox(`${(b.kind||'REAL CASE').toUpperCase()} · ${b.title}`,[p(b.context),...list(b.points||[]),...(b.source?[p(`Source: ${b.source.label}${b.source.url?`: ${b.source.url}`:''}`)]:[])],'FFF8E8')]
    case 'timeline': return [h(b.title),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:b.items.map(item=>new TableRow({children:[new TableCell({borders,width:{size:22,type:WidthType.PERCENTAGE},shading:{type:ShadingType.CLEAR,fill:'EEF1FA'},children:[p([new TextRun({text:item.date,bold:true,color:colors.indigo})])]}),new TableCell({borders,children:[p([new TextRun({text:item.title,bold:true})]),p(item.text)]})]}))})]
    case 'comparison': return [h(b.title),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:b.columns.map(column=>new TableCell({borders,shading:{type:ShadingType.CLEAR,fill:'EEF1FA'},children:[p([new TextRun({text:column,bold:true})])]}))}),...b.rows.map(row=>new TableRow({children:row.map(cell=>new TableCell({borders,children:[p(cell)]}))}))]})]
    case 'source-note': return [tableBox(b.label||'SOURCE NOTE',[p(b.claim),...(b.url?[p(b.url)]:[]),...(b.verifiedThrough?[p(`Verified through ${b.verifiedThrough}`)]:[])],'EEF8F6')]
    case 'question': return [tableBox(b.kind==='verified-pyq'?'VERIFIED PAST-YEAR QUESTION':'PRACTICE QUESTION',[p([new TextRun({text:[b.exam,b.year,b.paper,b.marks&&`${b.marks} marks`].filter(Boolean).join(' · '),italics:true,color:'596579'})]),p([new TextRun({text:b.prompt,bold:true})]),p([new TextRun({text:'Model answer: ',bold:true,color:colors.teal}),...rich(b.answer)]),...list(b.marking||[]),...(b.sourceUrl?[p(`Official source: ${b.sourceUrl}`)]:[])],b.kind==='verified-pyq'?'EEF8F6':'FFF8E8')]
    case 'activity': return [tableBox(`ACTIVITY · ${b.title}`,[...(b.materials?.length?[p(`Materials: ${b.materials.join(', ')}`)]:[]),...list(b.steps,'steps'),...(b.safety?[p([new TextRun({text:'Safety: ',bold:true,color:'9A5B00'}),...rich(b.safety)])]:[])],'EEF8F6')]
    case 'challenge': return [tableBox(`SKILL TRIAL · ${b.rank} · ${b.title}`,[p(b.brief),...list(b.steps,'steps'),p([new TextRun({text:'Win condition: ',bold:true,color:colors.teal}),...rich(b.winCondition)]),...(b.stretch?[p([new TextRun({text:'Stretch move: ',bold:true,color:colors.indigo}),...rich(b.stretch)])]:[])],'FFF8E8')]
    case 'victory': return [tableBox(`RANK EARNED · ${b.rank}`,[p('You proved that you can:'),...list(b.proof),p([new TextRun({text:'Next target: ',bold:true,color:colors.indigo}),...rich(b.next)])],'EAF8F4')]
    case 'arithmetic-exercise': return [tableBox('SIMPLE EXERCISE · Numbers: Simple Arithmetic',[p('Write an expression that equals 100.'),p([new TextRun({text:'Examples: ',bold:true}),...rich('`50 + 50` or `110 - 10`.')]),p('See if you can use more than one arithmetic operator. Write only one expression and submit only one line of code.'),p([new TextRun({text:'Success check: ',bold:true}),new TextRun('If your expression results in 100, your solution is correct.')])],'EEF8F6')]
    case 'reflection': return [tableBox('OPTIONAL REFLECTION',[p(b.prompt),p(b.permission||'You may pause, skip this exercise or return later.'),...list(b.guidance||[])],'F3F0FA')]
    case 'safety-notice': return [tableBox(b.title||'IMPORTANT SUPPORT NOTE',[p(b.text),...(b.resources||[]).map(([label,url])=>p(`${label}: ${url}`))],'FFF0F0')]
    default:return []
  }
}
async function blocksToDocx(blocks){ const out=[]; for(const block of blocks) out.push(...await blockToDocx(block)); return out }
export async function buildBookDocument(publication){
  const { lessons, BOOK, BRAND, PREFACE, HOW_TO_READ, QUICK_START } = publication
  const imprintMark = await imageLoader(BRAND.imprintMark)
  const front=[new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:900,after:260},children:[new ImageRun({data:imprintMark,type:'png',transformation:{width:96,height:96},altText:{title:`${BRAND.imprint} publisher mark`,description:'Circular publisher mark showing a young scholar writing in an open book.',name:'Publisher mark'}})]}),p(BRAND.imprint.toUpperCase(),{alignment:AlignmentType.CENTER,spacing:{after:160}}),p(BRAND.tagline,{alignment:AlignmentType.CENTER,spacing:{after:400}}),p([new TextRun({text:BOOK.title,bold:true,size:52,color:colors.navy})],{alignment:AlignmentType.CENTER}),p([new TextRun({text:BOOK.subtitle,size:30,color:colors.indigo})],{alignment:AlignmentType.CENTER}),p(`${BOOK.series}\n${BOOK.author}\n${BOOK.edition} · ${BOOK.year}`,{alignment:AlignmentType.CENTER,spacing:{before:500}}),new Paragraph({children:[new PageBreak()]}),h(BOOK.title,HeadingLevel.HEADING_1),p([new TextRun({text:`© ${BOOK.year} by ${BOOK.author}. All rights reserved.`,bold:true})]),p(`Published by ${BOOK.publisher}.`),p(BOOK.rights),p(BOOK.disclaimer),p([new TextRun({text:BOOK.dedication,italics:true,color:colors.indigo})]),new Paragraph({children:[new PageBreak()]}),h('Acknowledgements',HeadingLevel.HEADING_1),...BOOK.acknowledgements.map(text=>p(text)),new Paragraph({children:[new PageBreak()]}),h('Contents',HeadingLevel.HEADING_1),new TableOfContents('Table of Contents',{hyperlink:true,headingStyleRange:'1-1'}),p('In Microsoft Word, right-click this list and choose Update Field if page numbers are not visible.'),new Paragraph({children:[new PageBreak()]}),h(PREFACE.title,HeadingLevel.HEADING_1),...(await blocksToDocx(PREFACE.blocks))]
  if (HOW_TO_READ) front.push(new Paragraph({children:[new PageBreak()]}),h(HOW_TO_READ.title,HeadingLevel.HEADING_1),...(await blocksToDocx(HOW_TO_READ.blocks)))
  if (QUICK_START) front.push(new Paragraph({children:[new PageBreak()]}),p([new TextRun({text:'QUICK START',bold:true,size:18,color:colors.indigo,characterSpacing:24})]),h(QUICK_START.title,HeadingLevel.HEADING_1),p([new TextRun({text:QUICK_START.subtitle,italics:true,color:'596579'})]),...(await blocksToDocx(QUICK_START.blocks)))
  const body=[]; for(let i=0;i<lessons.length;i++){const l=lessons[i];body.push(new Paragraph({pageBreakBefore:true,spacing:{after:100},children:[new TextRun({text:`${BOOK.unitLabel.toUpperCase()} ${String(i+1).padStart(2,'0')}`,bold:true,size:18,color:colors.indigo,characterSpacing:24})]}),new Paragraph({heading:HeadingLevel.HEADING_1,spacing:{after:140},children:[new TextRun({text:l.title,bold:true,size:48,color:colors.navy})]}),p([new TextRun({text:l.subtitle,italics:true,color:'596579'})]),...(await blocksToDocx(l.blocks)))}
  body.push(new Paragraph({pageBreakBefore:true,heading:HeadingLevel.HEADING_1,children:[new TextRun({text:'About the author',bold:true,color:colors.navy})]}),...BOOK.aboutAuthor.map(text=>p(text)),h('Keep learning'),p('Keep guessing, running and checking.'),p([new TextRun({text:`${BRAND.imprint} · ${BRAND.tagline}`,bold:true,color:colors.indigo})]))
  return new Document({features:{updateFields:true},styles:{default:{document:{run:{font:'Calibri',size:22,color:colors.text},paragraph:{spacing:{line:300,after:120}}}},paragraphStyles:[{id:'Heading1',name:'Heading 1',basedOn:'Normal',next:'Normal',quickFormat:true,run:{font:'Calibri',size:34,bold:true,color:colors.navy},paragraph:{spacing:{before:300,after:160},keepNext:true,outlineLevel:0}},{id:'Heading2',name:'Heading 2',basedOn:'Normal',next:'Normal',quickFormat:true,run:{font:'Calibri',size:27,bold:true,color:colors.indigo},paragraph:{spacing:{before:260,after:120},keepNext:true,outlineLevel:1}},{id:'Heading3',name:'Heading 3',basedOn:'Normal',next:'Normal',quickFormat:true,run:{font:'Calibri',size:23,bold:true,color:colors.teal},paragraph:{keepNext:true,outlineLevel:2}}]},numbering:{config:[{reference:'bullet',levels:[{level:0,format:'bullet',text:'•',alignment:AlignmentType.LEFT,style:{paragraph:{indent:{left:500,hanging:240}}}}]},{reference:'steps',levels:[{level:0,format:'decimal',text:'%1.',alignment:AlignmentType.LEFT,style:{paragraph:{indent:{left:500,hanging:240}}}}]}]},sections:[{properties:{page:{margin:{top:900,right:900,bottom:900,left:900}}},headers:{default:new Header({children:[p(`${BOOK.title}  ·  ${BOOK.author}`,{alignment:AlignmentType.RIGHT})]})},footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun('Page '),new TextRun({children:[PageNumber.CURRENT]}),new TextRun(' of '),new TextRun({children:[PageNumber.TOTAL_PAGES]})]})]})},children:[...front,...body]}]})
}
export async function exportBookToWord(publication){const doc=await buildBookDocument(publication);const blob=await Packer.toBlob(doc);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=publication.BOOK.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}
