export const chapter07 = {
  id: 'split-and-share-code', icon: '↗', title: 'Split and Share Code', shortTitle: 'Modules',
  subtitle: 'Split one crowded file into understandable modules and run it in an isolated environment.', tags: ['Codebase map', 'Modules', '50 min'],
  blocks: [
    { type: 'arc-progress', arcTitle: 'Rescue and Strengthen an Application', step: 2, total: 3, currentFocus: 'Create a clear codebase map', text: 'Separate models, application logic, entry code and tests.' },
    { type: 'definition', term: 'module and package', text: 'A **module** is a Python file that can be imported. A **package** groups related modules under a package name.' },
    { type: 'flow', title: 'The assistant import map', stages: [{ eyebrow: 'ENTRY', title: '`main.py`', detail: 'Starts the program and calls application logic.' }, { eyebrow: 'LOGIC', title: '`assistant.py`', detail: 'Chooses command behavior and uses models.' }, { eyebrow: 'MODEL', title: '`models.py`', detail: 'Defines `Note` and its behavior.' }, { eyebrow: 'PROOF', title: '`tests/test_assistant.py`', detail: 'Imports public behavior and checks results.' }], caption: 'Arrows should point from the importer to the responsibility it needs. Clear direction helps prevent circular imports.' },
    { type: 'heading', text: 'Import names clearly' },
    { type: 'paragraph', text: '`import models` keeps qualification visible, as in `models.Note(...)`. `from models import Note` brings one name into the current module. Avoid `from models import *` because readers cannot easily see where names came from.' },
    { type: 'code', filename: 'main.py', lines: ['from assistant import run', '', 'def main():', '    run()', '', 'if __name__ == "__main__":', '    main()'] },
    { type: 'paragraph', text: 'Python sets `__name__` to `"__main__"` when a file is run directly. When another module imports that file, `__name__` is its module name. The guard prevents start-up code from running during import.' },
    { type: 'guess', prompt: 'What runs when a test imports `main`?', code: 'if __name__ == "__main__":\n    main()', options: ['main() always runs', 'main() does not run during the import', 'Python raises an error'], answerIndex: 1, explain: 'During import, the module name is not `__main__`.' },
    { type: 'heading', text: 'Know where a package comes from' },
    { type: 'comparison', title: 'Three sources of imports', columns: ['Kind', 'Example', 'Installed how'], rows: [['Your module', '`models`', 'It is part of your project.'], ['Standard library', '`pathlib`', 'It ships with Python.'], ['Third-party package', 'A reviewed package from PyPI', 'Install it into the project environment.']] },
    { type: 'heading', text: 'Isolate project tools with `.venv`' },
    { type: 'steps', showHeading: false, items: ['Open the Command Palette in VS Code.', 'Choose **Python: Create Environment** and select **Venv**.', 'Select the Python interpreter. VS Code creates `.venv` and selects it.', 'Use **Python: Select Interpreter** if you need to select it again.', 'Open a VS Code terminal. Use `python -m pip install package-name` only for a package you have reviewed and need.', 'Record exact direct dependencies in the project dependency file. Use the project instructions to rebuild the environment.'] },
    { type: 'callout', variant: 'note', title: 'pip and PyPI are different', paragraphs: ['**pip** is an installer. **PyPI** is a public package index. Inspect the package name, owner, documentation, release history and project need before installation.', 'Remove an unneeded package with `python -m pip uninstall package-name`. Never paste secrets into package commands or project files.'] },
    { type: 'bug', prompt: 'Why is this import design risky?', lines: ['# models.py', 'from assistant import run', '# assistant.py', 'from models import Note'], bugLine: 2, explain: 'The files depend on each other while importing. Move shared definitions into a lower-level module with one-way dependencies.' },
    { type: 'quiz', items: [['What is a module?', 'A Python file that can be imported.'], ['Why qualify a name as `models.Note`?', 'It makes the source module visible.'], ['What does the main guard prevent?', 'Program start-up code running merely because a module was imported.'], ['Why use a virtual environment?', 'To isolate project packages from other projects and the system installation.']] },
    { type: 'takeaways', items: ['Modules separate responsibilities.', 'A main guard creates a safe entry point.', 'A virtual environment isolates dependencies.'] },
    { type: 'resources', items: [['Python modules', 'https://docs.python.org/3/tutorial/modules.html'], ['Python packaging guide', 'https://packaging.python.org/en/latest/tutorials/installing-packages/'], ['VS Code Python environments', 'https://code.visualstudio.com/docs/python/environments']] },
    { type: 'cliffhanger', title: 'Organization does not prove correctness', text: 'Next, tracebacks, specific exception handling and automated tests complete the reliability trial.' }
  ]
}
