import divisionImage from '../assets/numbers-division.png'
import orderImage from '../assets/expression-order.png'

const codeLines = ['score = 25', 'score = score * 3', 'score = score + 25', 'print(score)']

export const lesson05 = {
  id: 'numbers', icon: '💯', title: 'Numbers: Build a 100-Point Score', shortTitle: 'Numbers',
  subtitle: 'Use Python’s number operators, predict each step and land exactly on 100.', tags: ['Numbers', 'Operators', '20 min'],
  blocks: [
    { type: 'arc-progress', arcTitle: 'Create a Local Study Assistant', step: 5, total: 5, currentFocus: 'Calculate and test values', variant: 'build', label: 'BUILD CHALLENGE', title: 'Reach exactly 100 points', text: 'Begin with 25. Use at least two number operations. Make Python finish on exactly 100, then explain every step.', weKnowLabel: 'Build materials', weNeedLabel: 'Success checks', weKnow: ['A variable can remember the current score.', '`+`, `-` and `*` change numbers.'], weNeed: ['Use at least two operators.', 'Predict the value after every line.', 'Print exactly `100`.'] },
    { type: 'think', prompt: 'Which two operations could turn 25 into 100?', answer: 'One route is `25 * 3`, then `75 + 25`. The result is 100. Other correct routes are possible.' },
    { type: 'heading', text: 'Meet Python’s seven number operators' },
    { type: 'paragraph', text: 'An **operator** is a symbol that tells Python to perform a calculation. Each expression below uses two numbers called **operands**.' },
    { type: 'comparison', title: 'Operator toolkit', columns: ['Operator', 'Job', 'Example', 'Result'], rows: [
      ['`+`', 'add', '`7 + 4`', '`11`'],
      ['`-`', 'subtract', '`7 - 4`', '`3`'],
      ['`*`', 'multiply', '`7 * 4`', '`28`'],
      ['`/`', 'true division', '`7 / 4`', '`1.75`'],
      ['`//`', 'floor division', '`7 // 4`', '`1`'],
      ['`%`', 'remainder', '`7 % 4`', '`3`'],
      ['`**`', 'raise to a power', '`2 ** 3`', '`8`'],
    ] },
    { type: 'callout', variant: 'note', title: 'Python symbols are not always textbook symbols', paragraphs: ['Python uses `*` for multiplication and `**` for powers. A keyboard has both characters.', 'The `/` operator returns a floating-point number. For example, `8 / 2` produces `4.0`.'] },
    { type: 'heading', text: 'One division, three useful questions' },
    { type: 'think', prompt: 'Seven counters are placed in groups of four. How many whole groups fit, and how many counters remain?', answer: 'One whole group fits. Three counters remain. Python can report the complete quotient, the number of whole groups or the remainder.' },
    { type: 'image', src: divisionImage, file: 'src/books/technical/programming/python-absolute-beginners/editions/edition-01/assets/numbers-division.png', w: 1200, h: 650, alt: 'Seven counters are compared using three division operators. Seven divided by four is 1.75, seven floor-divided by four is 1, and seven remainder four is 3.', caption: 'The operators answer different questions about the same seven counters.' },
    { type: 'worked-example', title: 'Choose the operator that matches the question', problem: 'Seven learners form teams of four. Report the exact quotient, complete teams and learners left over.', steps: ['Use `7 / 4` for the complete quotient: `1.75`.', 'Use `7 // 4` for the count of complete teams: `1`.', 'Use `7 % 4` for the learners left over: `3`.'], result: '`1.75`, `1` and `3` describe different parts of the same grouping.' },
    { type: 'callout', variant: 'note', title: 'Floor division has a precise rule', paragraphs: ['For positive whole numbers, `//` gives the number of complete groups. More precisely, it rounds the division result down toward negative infinity.', 'We will practise positive counters here. This keeps our grouping picture simple.'] },
    { type: 'heading', text: 'Use the remainder to check even numbers' },
    { type: 'paragraph', text: 'A positive integer is **even** when division by 2 leaves no remainder. That makes `number % 2 == 0` a useful check. The double equals sign asks whether two values are equal.' },
    { type: 'worked-example', title: 'Is 24 even?', problem: 'Check whether 24 can be split into pairs with nothing left over.', steps: ['Calculate `24 % 2`.', 'The remainder is `0`.', 'Therefore `24 % 2 == 0` is `True`.'], result: 'For this positive-integer check, 24 is even.' },
    { type: 'guess', prompt: 'Which expression becomes True?', code: 'number = 17', options: ['number % 2 == 0', 'number % 2 == 1', 'number // 2 == 0'], answerIndex: 1, explain: '17 leaves remainder 1 when divided by 2.' },
    { type: 'heading', text: 'Powers mean repeated factors' },
    { type: 'paragraph', text: 'An **exponent** tells us how many equal factors to multiply. In `2 ** 3`, the base is 2 and the exponent is 3. The expression means `2 * 2 * 2`, so its value is 8.' },
    { type: 'think', prompt: 'Is `3 ** 4` the same as `3 * 4`?', answer: 'No. `3 ** 4` means `3 * 3 * 3 * 3`, which is 81. `3 * 4` is 12.' },
    { type: 'heading', text: 'Python follows an order of operations' },
    { type: 'paragraph', text: 'Python evaluates parentheses first, then powers, then multiplication and division operators, then addition and subtraction. Operators at the same level normally run from left to right. Exponentiation has special right-associative behavior, which we can explore later.' },
    { type: 'image', src: orderImage, file: 'src/books/technical/programming/python-absolute-beginners/editions/edition-01/assets/expression-order.png', w: 1200, h: 600, alt: 'Two calculations show that 2 plus 10 times 10 plus 3 is 105, while open parenthesis 2 plus 10 close parenthesis times open parenthesis 10 plus 3 close parenthesis is 156.', caption: 'Parentheses make the intended groups visible and can change the result.' },
    { type: 'callout', variant: 'note', title: 'Clear code beats a memory trick', paragraphs: ['Use parentheses when they make your intended calculation easier to read, even when Python would already choose the same order.', 'Do not add random parentheses. Group the parts that belong together.'] },
    { type: 'heading', text: 'Build the 100-point score' },
    { type: 'blueprint', showHeading: false, purpose: 'Start at 25 and finish at exactly 100.', input: 'Starting score: 25.', processing: 'Multiply by 3, then add 25.', output: '100', files: ['score_100.py'] },
    { type: 'code', filename: 'score_100.py', lines: codeLines },
    { type: 'guess', prompt: 'What value will the program print?', code: codeLines.join('\n'), options: ['50', '75', '100'], answerIndex: 2, explain: '25 times 3 is 75. Adding 25 gives 100.' },
    { type: 'runviz', filename: 'score_100.py', codeLines, steps: [
      { line: null, title: 'Memory starts empty', explain: 'No score exists yet.', vars: [], console: [] },
      { line: 1, title: 'Store the starting score', explain: 'score refers to 25.', vars: [{ name: 'score', value: '25' }], console: [] },
      { line: 2, title: 'Triple the score', explain: 'Python calculates 25 * 3 and assigns 75 back to score.', vars: [{ name: 'score', value: '75' }], console: [] },
      { line: 3, title: 'Add the final 25', explain: 'Python calculates 75 + 25 and assigns 100.', vars: [{ name: 'score', value: '100' }], console: [] },
      { line: 4, title: 'Display the result', explain: 'print() displays the current value.', vars: [{ name: 'score', value: '100' }], console: ['100'] },
    ] },
    { type: 'terminal', command: 'python score_100.py', lines: ['100'] },
    { type: 'arithmetic-exercise' },
    { type: 'callout', variant: 'warning', title: 'Division by zero stops the calculation', paragraphs: ['Python cannot calculate `10 / 0`, `10 // 0` or `10 % 0`. Each raises a `ZeroDivisionError`.', 'When a divisor might come from a changing value, check that it is not zero before dividing. We will learn decision-making code in a later lesson.'] },
    { type: 'callout', variant: 'note', title: 'Some decimal results are approximations', paragraphs: ['Computers store most floating-point values in a finite binary form. Some familiar decimals cannot be represented exactly.', 'For example, Python may display `0.1 + 0.2` as `0.30000000000000004`. This is normal floating-point approximation, not a broken addition operator. We will learn suitable comparison and rounding tools later.'] },
    { type: 'bug', prompt: 'Which line causes the program to stop?', lines: ['points = 100', 'teams = points // 0', 'print(teams)'], bugLine: 2, explain: 'Floor division by zero raises ZeroDivisionError.' },
    { type: 'mistakes', items: [['2 ^ 3', 'The power operator is **. The ^ symbol has a different meaning in Python.'], ['7 / 4 == 1', 'True division gives 1.75. Use // only when the floor result answers your question.'], ['score * 2 = score', 'Assignment needs a variable name on the left: score = score * 2.']] },
    { type: 'quiz', items: [['For `17 % 5` and `17 // 5`, what are the two results?', '`17 % 5` is 2, the remainder. `17 // 5` is 3, the floored quotient.'], ['What does `3 ** 4` mean?', 'Multiply four factors of 3: 3 * 3 * 3 * 3, which is 81.'], ['Which part runs first in `(8 + 2) * 5`?', 'The parenthesized addition runs first, producing 10.'], ['What error does `5 / 0` raise?', 'ZeroDivisionError.']] },
    { type: 'takeaways', items: ['Python uses `+`, `-`, `*`, `/`, `//`, `%` and `**` for number operations.', '`/`, `//` and `%` answer different division questions.', 'For a positive integer, a remainder of zero after `% 2` means the number is even.', 'Powers represent repeated equal factors.', 'Parentheses make arithmetic groups clear.', 'Division by zero raises `ZeroDivisionError`.', 'Floating-point results can be close approximations.'] },
    { type: 'resources', items: [['Python arithmetic conversions and operators', 'https://docs.python.org/3/reference/expressions.html#binary-arithmetic-operations'], ['Python numeric types', 'https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-complex'], ['Python floating-point tutorial', 'https://docs.python.org/3/tutorial/floatingpoint.html']] },
    { type: 'cliffhanger', title: 'A program needs information from its reader', text: 'Next, we will let a person type a value while the program is running.' },
  ],
}
