export const CURRICULUM_ROADMAP = [
  {
    phase: 'Mission 1',
    title: 'The Core Protocol and Campus Cloud Integration',
    description: 'Resolving the campus interoperability crisis, inspecting the invisible network wire, decoding the HTTP protocol with live catalog endpoints, exploring REST CRUD architecture, and assembling collaborative Postman suites.',
    modules: [
      {
        id: 'understanding-apis',
        title: 'Understanding APIs from First Principles',
        topics: [
          'What is an API? The Campus Interoperability Crisis',
          'The Restaurant Analogy: Customer, Waiter, and Kitchen Backend',
          'Real World Case: How Partner Portals and Aggregators Integrate',
          'Frontend and Backend Decoupling over HTTP and JSON',
          'Hands On: Inspecting Live Campus Catalog Endpoints in Your Browser',
        ],
        assessment: 'API Fundamentals Knowledge Check',
      },
      {
        id: 'rest-crud-status',
        title: 'REST Architecture and HTTP Methods',
        topics: [
          'Representational State Transfer (REST) Core Principles',
          'The 4 CRUD Operations: Create, Read, Update, Delete',
          'The Restaurant Bill Story: GET, POST, PUT, PATCH, and DELETE',
          'Idempotency: Safe vs Unsafe Operations',
          'The 5 Status Code Families from 100 to 599',
          'Live Status Code Verification: 200, 201, 404, and 500',
        ],
        assessment: 'HTTP Methods and Status Code Challenge',
      },
      {
        id: 'postman-setup',
        title: 'Setting Up Postman and Workspace Collaboration',
        topics: [
          'Why We Need an API Testing Workbench',
          'Postman and Modern Alternatives like Bruno',
          'Desktop Application Installation and Account Setup',
          'Workspace Scopes: Personal, Team, and Public Workspaces',
          'Team Collaboration: Forking Collections and Reviewing Pull Requests',
          'Executing Live Requests in Your Postman Collection',
        ],
        assessment: 'Mission 1 Accomplished: Live REST Collection Verified',
      },
    ],
    milestone: {
      type: 'project',
      badge: 'Milestone 1',
      title: 'Live REST Protocol and Collection Verification',
      summary: 'Inspect live HTTP wire packets, test real CRUD requests, verify status codes, and assemble an executable suite in Postman.',
    },
  },
  {
    phase: 'Mission 2',
    title: 'Automating Student and Campus Services at Scale',
    description: 'Constructing an automated, parameterized, chained regression pipeline for the College Library API, parsing nested JSON arrays, and ingesting hundreds of records via Data Driven Testing.',
    modules: [
      {
        id: 'library-crud',
        title: 'Manual Testing the College Library API',
        topics: [
          'The Library API Contract across QA and UAT Targets',
          'AddBook POST: JSON Payloads, Composite IDs, and Unique Constraints',
          'GetBook GET: Query Parameters and Retrieval',
          'DeleteBook POST: Idempotent Database Cleanup',
          'Identifying the Pain of Manual Copy Paste',
        ],
        assessment: 'Manual CRUD Lifecycle Verification',
      },
      {
        id: 'javascript-assertions',
        title: 'Writing JavaScript Assertions and the pm Object',
        topics: [
          'The Embedded Node.js Execution Sandbox',
          'Writing Assertions with pm.test() and Chai Matchers',
          'Validating HTTP Status Codes and Header Content',
          'Response Latency Budgets under 1200 Milliseconds',
          'JSON Schema Validation with Built In Ajv',
        ],
        assessment: 'Automated Assertion Suite Implementation',
      },
      {
        id: 'variables-and-scopes',
        title: 'Managing Variables Across the Five Scopes',
        topics: [
          'The 5 Variable Scopes: Local, Data, Environment, Collection, Global',
          'Scope Precedence Ladder and Conflict Resolution',
          'Dynamic Base URL Switching between QA and UAT',
          'Initial Value vs Current Value Security Mechanics',
          'Pre request Dynamic Unique ISBN Generation',
        ],
        assessment: 'Multi Scope Variable Matrix',
      },
      {
        id: 'request-chaining',
        title: 'Request Chaining and Complex Nested JSON Parsing',
        topics: [
          'Dynamic Property Transfer from AddBook to Downstream Calls',
          'Traversing Nested Objects and Multilevel JSON Hierarchies',
          'Manipulating Arrays with JavaScript find, filter, and map',
          'Mathematical Aggregation across Nested Items using reduce and Loops',
          'The Campus Bookstore E Commerce Transaction Flow',
          'Multipart Form Data with Binary Cover Image Uploads',
          'Automated Teardown Cleanup of Orders and Products',
        ],
        assessment: 'End to End Chained Pipeline and Nested Data Verification',
      },
      {
        id: 'data-driven-testing',
        title: 'Data Driven Testing with External Data Files',
        topics: [
          'Decoupling Test Logic from External Test Data',
          'Reading CSV Datasets with pm.iterationData.get()',
          'Catching Variable Resolution Bugs in the Console',
          'Iterating Test Suites Across Hundreds of Book Records',
        ],
        assessment: 'Mission 2 Accomplished: Library Automation at Full Scale',
      },
    ],
    milestone: {
      type: 'project',
      badge: 'Milestone 2',
      title: 'Autonomous Library Ingestion Engine',
      summary: 'A fully parameterized, self cleaning test suite driving hundreds of book insertions from external files.',
    },
  },
  {
    phase: 'Mission 3',
    title: 'Enterprise Resilience, Mock Servers, and CI CD Pipelines',
    description: 'Hardening test suites with negative matrices, defensive safe parsing, Postman mock servers, JSON Schema contract testing, OAuth 2.0 token security, SOAP WebServices, and headless Newman continuous integration.',
    modules: [
      {
        id: 'error-handling-resilience',
        title: 'Advanced Error Handling and Resilience Testing',
        topics: [
          'The Production Negative Testing Matrix (400, 401, 404, 429, 500)',
          'Defensive Scripting: Safe Parsing with Try Catch Blocks',
          'Guarding Against Sensitive Database Stack Trace Leaks',
          'Soft Error Detection: Status 200 with Hidden Error Content',
          'Self Healing Retry Workflows with Collection Flags',
        ],
        assessment: 'Resilience and Negative Matrix Verification',
      },
      {
        id: 'mock-servers-and-contracts',
        title: 'Postman Mock Servers and JSON Schema Contracts',
        topics: [
          'Contract First API Development and JSON Schema Fundamentals',
          'Identifying Field Type Mismatches and Missing Properties',
          'Schema Validation in Postman using tv4 and Ajv Libraries',
          'The Agile Dilemma: Unblocking Frontend and QA Teams Early in Sprints',
          'Creating Postman Mock Servers and Mocking Responses with Examples',
          'Matching Query Parameters for Custom Mock Payloads',
          'Modern Query Architectures: Testing GraphQL Alongside REST',
          'GraphQL Schemas, Types, Queries, Query Variables, and Mutations',
        ],
        assessment: 'Mock Server and JSON Schema Contract Verification',
      },
      {
        id: 'oauth-token-auth',
        title: 'OAuth 2.0 and Modern Token Authentication',
        topics: [
          'Why Modern APIs Rely on OAuth 2.0 (The Hotel Keycard Analogy)',
          'The Four Roles: Resource Owner, Client, Authorization Server, Resource Server',
          'The Two Step Authorization Code Handshake Contract',
          'Mandatory Parameters for Authorization Code Retrieval',
          'Mandatory Parameters for Token Exchange Requests',
          'Automated Token Generation in Pre request and Test Scripts',
          'Storing Bearer Tokens in Global Variables for Automated Chaining',
          'Testing Token Expiry and 401 Unauthorized Responses',
        ],
        assessment: 'OAuth 2.0 Handshake Verification',
      },
      {
        id: 'soap-and-xml',
        title: 'SOAP WebServices and XML Parsing',
        topics: [
          'REST vs SOAP Architectural Differences and WSDL Contracts',
          'Anatomy of a SOAP Message: Envelopes, Headers, Bodies, and Faults',
          'Executing Live SOAP Requests in Postman with Content Type text/xml',
          'Parsing XML Strings into JavaScript Objects using xml2Json',
          'Asserting SOAP Response Values with Bracket Notation for Namespaces',
        ],
        assessment: 'SOAP XML Envelope Validation',
      },
      {
        id: 'newman-cicd-execution',
        title: 'Headless Test Execution with Newman and CI CD',
        topics: [
          'Running Collections Headlessly via Newman CLI',
          'Exporting Portable Collection and Environment Artifacts',
          'Fail Fast Execution with the Bail Flag',
          'Generating Interactive HTML Extra Dashboards',
          'Gating Deployments in Jenkins and GitHub Actions',
          'Scheduled Cloud Quality with Postman Monitors',
          'Workspace History Logs and Trash Recovery',
        ],
        assessment: 'Mission 3 Accomplished: Autonomous Production Quality Gate',
      },
    ],
    milestone: {
      type: 'capstone',
      badge: 'Final Capstone Project',
      title: 'Enterprise CI CD Quality Gate',
      summary: 'An autonomous pipeline executing resilient Newman regression suites and publishing visual HTML reports on every code commit.',
    },
  },
]
