import chainingImg from '../assets/api-request-chaining-pipeline.jpg'
import arrayPipelineImg from '../assets/javascript-array-pipeline-transform.jpg'

export const lesson07 = {
  id: 'request-chaining',
  icon: '',
  title: 'Request Chaining and Complex Nested JSON Parsing',
  shortTitle: 'Request Chaining and Parsing',
  subtitle: 'Automated property transfer, navigating nested object hierarchies, array methods, and mathematical calculations.',
  tags: ['Chaining', 'Property Transfer', 'Nested JSON', 'Array Methods', 'Calculations'],
  blocks: [
    {
      type: 'mission-tracker',
      badge: 'MISSION 2 PROGRESS · STEP 4 OF 5',
      title: 'Continuing Mission 2: Assembling the Autonomous Pipeline',
      text: 'Our AddBook request is now parameterized and unique, but we are still manually copying the generated book ID into GetBook and DeleteBook. Our next step in Mission 2 is assembling an autonomous regression pipeline: capturing the response ID automatically, passing it downstream via environment variables, navigating complex nested JSON structures, filtering and mapping arrays, and validating business calculations across multi step transactions.',
    },
    {
      type: 'heading',
      text: 'Step 1: The Three Stage Request Chaining Pipeline',
    },
    {
      type: 'image',
      layout: 'stacked',
      badge: 'REQUEST PIPELINE',
      title: 'Dynamic Request Chaining: Passing Identity Between Dependent Calls',
      text: 'By storing dynamic outputs into variables, a collection can execute dozens of interdependent requests in complete harmony. Subsequent requests consume dynamic keys in their URLs, headers, or request bodies automatically, eliminating all manual copy paste intervention.',
      src: chainingImg,
      file: 'src/books/technical/programming/testing/zero-to-agentic-api-testing/editions/edition-01/assets/api-request-chaining-pipeline.jpg',
      w: 1408,
      h: 768,
      alt: 'Flowchart showing request chaining pipeline: Step 1 AddBook POST creates ID, Step 2 GetBook GET queries ID, Step 3 DeleteBook POST removes ID.',
      caption: 'The autonomous property transfer pipeline across three chained requests.',
      points: [
        'Step 1 (AddBook POST): Dispatches dynamic payload. Tests script extracts generated ID into environment variable book_id.',
        'Step 2 (GetBook GET): Injects {{book_id}} into query params and asserts that the stored author matches the creation author.',
        'Step 3 (DeleteBook POST): Reads {{book_id}} in the payload body and asserts that the record is completely removed.',
      ],
    },
    {
      type: 'heading',
      text: 'Step 2: Capturing and Storing the ID in AddBook',
    },
    {
      type: 'paragraph',
      text: 'In the Tests tab of AddBook, parse the response JSON and save the generated ID into an environment variable so downstream requests can immediately read it.',
    },
    {
      type: 'code',
      filename: 'addbook-property-transfer.js',
      lines: [
        'const responseData = pm.response.json();',
        'const generatedId = responseData.ID;',
        '',
        '// Save ID to Environment Scope for downstream requests',
        'pm.environment.set("book_id", generatedId);',
      ],
    },
    {
      type: 'heading',
      text: 'Step 3: Handling JSON Arrays and Validating ID Calculation',
    },
    {
      type: 'paragraph',
      text: 'GetBook returns a JSON array. In JavaScript, access the first record using zero index bracket notation: booksList[0].author.',
    },
    {
      type: 'code',
      filename: 'validate-id-and-author.js',
      lines: [
        '// Step 1: Parse outgoing request payload to verify business calculation',
        'const requestPayload = JSON.parse(pm.request.body.raw);',
        'const expectedCompositeId = requestPayload.isbn + requestPayload.aisle;',
        '',
        '// Step 2: Assert backend ID equals ISBN + aisle',
        'const responsePayload = pm.response.json();',
        'pm.test("Backend generated ID correctly concatenates ISBN and aisle", function () {',
        '    pm.expect(responsePayload.ID).to.eql(expectedCompositeId);',
        '});',
      ],
    },
    {
      type: 'heading',
      text: 'Step 4: Navigating Complex Nested JSON and Array Methods',
    },
    {
      type: 'paragraph',
      text: 'Real enterprise APIs rarely return flat, simple objects. Instead, responses contain nested hierarchies with multiple layers of parent objects, metadata summaries, and arrays of detailed items. Consider the Campus Library department audit endpoint below. You can download the sample payload: [Download Department Audit Response JSON](/materials/zero-to-agentic-api-testing/lesson-07/department-audit-response.json):',
    },
    {
      type: 'code',
      filename: 'nested-department-response.json',
      lines: [
        '{',
        '  "department": "Computer Science and Systems",',
        '  "budget": {',
        '    "total_allocated": 1500,',
        '    "currency": "USD"',
        '  },',
        '  "books": [',
        '    {',
        '      "id": "BK101",',
        '      "title": "Full Stack API Automation",',
        '      "author": "Dr. Sarah Chen",',
        '      "price": 45,',
        '      "copies": 12,',
        '      "tags": ["api", "testing", "javascript"]',
        '    },',
        '    {',
        '      "id": "BK102",',
        '      "title": "Postman Architecture Patterns",',
        '      "author": "Marcus Vance",',
        '      "price": 55,',
        '      "copies": 8,',
        '      "tags": ["postman", "architecture"]',
        '    },',
        '    {',
        '      "id": "BK103",',
        '      "title": "Distributed Systems Reliability",',
        '      "author": "Elena Rostova",',
        '      "price": 65,',
        '      "copies": 8,',
        '      "tags": ["cloud", "reliability"]',
        '    }',
        '  ]',
        '}',
      ],
    },
    {
      type: 'callout',
      variant: 'note',
      title: 'Four Essential JavaScript Array Methods for API Testers',
      paragraphs: [
        '• find(): Searches an array and returns the very first element matching a boolean condition.',
        '• filter(): Scans the entire array and returns a new array containing all elements that satisfy the condition.',
        '• map(): Transforms every element into a new representation, such as plucking a single property from an object array.',
        '• reduce(): Iterates through an array while accumulating a running total, ideal for verifying mathematical sums.',
      ],
    },
    {
      type: 'image',
      layout: 'stacked',
      badge: 'DATA TRANSFORMATION',
      title: 'JavaScript Array Transformation Pipeline: Filtering, Mapping, and Aggregating',
      text: 'Modern enterprise APIs deliver deep hierarchical payloads. Understanding how find, map, filter, and reduce transform JSON arrays allows automation engineers to locate specific records, compute expected financial aggregates, and assert mathematical integrity across entire catalogs.',
      src: arrayPipelineImg,
      file: 'src/books/technical/programming/testing/zero-to-agentic-api-testing/editions/edition-01/assets/javascript-array-pipeline-transform.jpg',
      w: 1408,
      h: 768,
      alt: 'JavaScript array transformation pipeline showing raw JSON array flowing into filter stage, map transformation stage, and reduce accumulation stage.',
      caption: 'The JavaScript Array Transformation Pipeline: Filtering, mapping, and reducing nested API data.',
      points: [
        'Stage 1 (Raw JSON Array): The incoming API response delivers an array of book objects containing titles and unit prices.',
        'Stage 2 (Filter Stage): books.filter() scans the array and extracts only items matching the condition (books priced above 30 dollars), discarding non matching records.',
        'Stage 3 (Map Stage): filteredBooks.map() transforms each item into a formatted line item object with calculated item totals.',
        'Stage 4 (Reduce Stage): mappedItems.reduce() accumulates each item total into a single running total, producing the final invoice sum of 126.',
      ],
    },
    {
      type: 'heading',
      text: 'Step 5: Writing Advanced Assertions: Finding, Filtering, and Summing',
    },
    {
      type: 'paragraph',
      text: 'Here is how we use these modern JavaScript methods inside Postman test scripts to verify complete schemas, locate target records, and validate mathematical integrity. You can download the script: [Download Advanced Array Assertions Script](/materials/zero-to-agentic-api-testing/lesson-07/advanced-array-assertions.js):',
    },
    {
      type: 'code',
      filename: 'advanced-nested-json-assertions.js',
      lines: [
        'const responseData = pm.response.json();',
        '',
        '// Test 1: Assert top level object and array size',
        'pm.test("Department audit returns valid book records", function () {',
        '    pm.expect(responseData.department).to.eql("Computer Science and Systems");',
        '    pm.expect(responseData.books).to.be.an("array").with.lengthOf(3);',
        '});',
        '',
        '// Test 2: Locate a specific book using find() and assert all keys exist',
        'pm.test("Locate Postman Architecture Patterns and verify its schema", function () {',
        '    const targetBook = responseData.books.find(book => book.title === "Postman Architecture Patterns");',
        '    pm.expect(targetBook, "Target book must exist").to.not.be.undefined;',
        '    pm.expect(targetBook.price).to.eql(55);',
        '    pm.expect(targetBook).to.have.all.keys("id", "title", "author", "price", "copies", "tags");',
        '});',
        '',
        '// Test 3: Extract titles using map() and filter premium books',
        'pm.test("Verify premium collection and extracted titles", function () {',
        '    const titles = responseData.books.map(book => book.title);',
        '    pm.expect(titles).to.include("Full Stack API Automation");',
        '',
        '    const premiumBooks = responseData.books.filter(book => book.price >= 50);',
        '    pm.expect(premiumBooks.length).to.eql(2);',
        '});',
        '',
        '// Test 4: Calculate mathematical sum using reduce()',
        'pm.test("Calculated purchase total matches allocated budget", function () {',
        '    const calculatedTotal = responseData.books.reduce(function (runningSum, book) {',
        '        return runningSum + (book.price * book.copies);',
        '    }, 0);',
        '',
        '    // (45 * 12 = 540) + (55 * 8 = 440) + (65 * 8 = 520) = 1500',
        '    pm.expect(calculatedTotal).to.eql(responseData.budget.total_allocated);',
        '});',
      ],
    },
    {
      type: 'callout',
      variant: 'tip',
      title: 'Fresher Trap to Avoid: Forgetting the Initial Value in reduce()',
      paragraphs: [
        'When using `array.reduce()` to calculate a sum, always provide `0` as the second argument: `reduce(function(...) { ... }, 0);`.',
        'If you omit the `0`, JavaScript sets the initial accumulator to the first object in the array rather than the number zero! Your addition will result in strange string concatenation errors like `[object Object]440520` instead of `1500`.',
        'Always supply `0` as the starting number when accumulating mathematical totals.',
      ],
    },
    {
      type: 'heading',
      text: 'Step 6: Real World Enterprise Flow: The Campus Bookstore Exchange',
    },
    {
      type: 'paragraph',
      text: 'In commercial software testing, QA engineers frequently automate multi step e commerce business transactions. In our campus system, students buy and sell laboratory textbooks and tech hardware through the Campus Bookstore Exchange. Let us examine the complete end to end transaction:',
    },
    {
      type: 'steps',
      items: [
        '1. Login and Session Token Capture: POST /v1/auth/login with student email and password. The Tests script extracts the JWT session token and stores it in a collection variable: pm.collectionVariables.set("session_token", response.token).',
        '2. Product Creation with Multipart Form Data: POST /v1/store/products. Instead of JSON, this endpoint requires multipart form data with fields like productName, price, and category, plus a binary textbook cover image attachment. In Postman, switch the key dropdown from Text to File to attach an image from your computer.',
        '3. Order Placement: POST /v1/store/orders with payload referencing {{product_id}}. The response returns an array of placed orders; the script extracts orderId from orders[0].',
        '4. Order Verification: GET /v1/store/orders?id={{order_id}} with header Authorization: Bearer {{session_token}}. Tests assert that the purchased item name matches the created product.',
        '5. Automated Teardown Cleanup: Once assertions pass, the suite calls DELETE /v1/store/orders/{{order_id}} and DELETE /v1/store/products/{{product_id}}. Cleaning up test records ensures that automated tests can run hundreds of times every day without polluting the database with fake inventory.',
      ],
    },
    {
      type: 'callout',
      variant: 'tip',
      title: 'Fresher Trap to Avoid: Postman Working Directory Warning on File Attachments',
      paragraphs: [
        'When attaching a file in Postman form data, you may see a warning indicating the file is outside Postman working directory.',
        'To resolve this in Postman: open Settings (or Preferences on macOS), navigate to the General tab, and enable the toggle: "Allow reading files outside working directory".',
        'Alternatively, place your sample image inside the default Postman working directory folder.',
      ],
    },
    {
      type: 'heading',
      text: 'Step 7: Executing the Suite with Collection Runner',
    },
    {
      type: 'terminal',
      command: 'Postman Collection Runner Execution Summary',
      lines: [
        '1. POST AddBook: 200 OK (210 ms) : 2 of 2 passed',
        '2. GET GetBook: 200 OK (145 ms) : 1 of 1 passed',
        '3. GET DepartmentAudit: 200 OK (185 ms) : 3 of 3 passed',
        '4. POST DeleteBook: 200 OK (160 ms) : 1 of 1 passed',
        '5. POST StoreLogin: 200 OK (120 ms) : 1 of 1 passed',
        '6. POST CreateProduct: 201 Created (190 ms) : 1 of 1 passed',
        '7. POST CreateOrder: 201 Created (175 ms) : 1 of 1 passed',
        '8. DELETE TeardownOrder: 200 OK (110 ms) : 1 of 1 passed',
        '9. DELETE TeardownProduct: 200 OK (105 ms) : 1 of 1 passed',
        'Collection Run Complete: 9 requests, 12 assertions, 0 failures (1300 ms)',
      ],
    },
    {
      type: 'heading',
      text: 'Step 8: Review and Practice',
    },
    {
      type: 'guess',
      prompt: 'If an API response returns an array of objects called courses, which JavaScript method finds the single course object whose title is "REST Automation"?',
      options: [
        'courses.find(item => item.title === "REST Automation")',
        'courses.get("REST Automation")',
        'courses.locate("REST Automation")',
        'courses.filterOne("REST Automation")',
      ],
      answerIndex: 0,
      explain: 'The find method evaluates each element in an array and returns the first element that satisfies the provided condition.',
    },
    {
      type: 'quiz',
      items: [
        [
          'What is property transfer in API test automation?',
          'Property transfer is capturing dynamic values from an earlier API response and injecting them into downstream request parameters or payloads.',
        ],
        [
          'Why must enterprise regression suites include automated teardown cleanup requests?',
          'Automated tests run continuously in CI CD pipelines. If tests do not delete the orders and products they create, test databases accumulate thousands of orphaned records, causing database bloat and false uniqueness failures.',
        ],
      ],
    },
    {
      type: 'takeaways',
      items: [
        'Request chaining connects isolated API calls into complete automated user journeys.',
        'Use environment variables to transfer identifiers across sequential requests.',
        'Use find to locate objects, filter to subset collections, and map to extract property lists.',
        'Use reduce to compute mathematical sums across nested arrays and assert business logic.',
        'Automated teardown steps clean up created resources, keeping test databases pure and idempotent.',
      ],
    },
    {
      type: 'victory-milestone',
      badge: 'MISSION 2 PHASE 4 CLEARED',
      rank: 'PRINCIPAL API TEST ARCHITECT',
      title: 'Architectural Triumph: Deep Array Pipelines & Request Chaining Mastered',
      summary: 'You linked disconnected HTTP requests into a living, breathing autonomous transaction pipeline. You extracted dynamic IDs, traversed multilevel nested objects without crash errors, performed high speed array transformations (find, filter, map), and mathematically verified financial balance totals using reduce. You operate at the highest echelon of API automation.',
      powers: [
        'Dynamic property transfer: piping tokens, session cookies, and resource IDs across multi request suites',
        'Deep nested JSON parsing: safely traversing multilevel object trees and arrays without null reference exceptions',
        'Functional array pipelines: wielding find, filter, and map to isolate specific records in complex payloads',
        'Mathematical business logic verification: aggregating invoice and catalog totals dynamically using reduce',
        'Zero footprint test execution: deploying automated teardown deletions that leave databases perfectly pristine',
      ],
      disastersPrevented: [
        'Averted silent financial balance discrepancies by verifying computed cart totals against backend invoices',
        'Stopped catastrophic test database pollution where uncleaned test orders exhaust database storage and IDs',
        'Eliminated brittle hardcoded test suites that crash whenever upstream backend developers alter resource IDs',
      ],
      warRoomTakeaway: 'Isolated API checks only test plumbing. Chained request pipelines test real world user journeys and business reality. When your chained suite passes, the entire business flow is guaranteed.',
    },
    {
      type: 'cliffhanger',
      title: 'Continuing Mission 2: Scaling to bulk inventory',
      text: 'Our chained pipeline and nested assertions work cleanly for single and nested requests. But what if a shipment of 100 new books arrives in a CSV spreadsheet? In Chapter 8, we complete Mission 2: driving bulk automated execution using external CSV and JSON data files!',
    },
  ],
}
