import cicdGateImg from '../assets/enterprise-cicd-quality-gate.jpg'
import newmanImg from '../assets/newman-ci-cd-pipeline.jpg'

export const lesson13 = {
  id: 'newman-cicd-execution',
  icon: '',
  title: 'Headless Test Execution with Newman and CI CD',
  shortTitle: 'Newman and CI CD',
  subtitle: 'Command line collection runs, rich HTML Extra reports, and automated pipeline integration.',
  tags: ['Newman', 'CLI', 'CI/CD', 'Jenkins', 'Reporting', 'Monitors'],
  blocks: [
    {
      type: 'mission-tracker',
      badge: 'MISSION 3 PROGRESS · STEP 5 OF 5',
      title: 'Completing Mission 3: Continuous Integration and Automated Gating',
      text: 'Tomorrow morning is the first day of semester enrollment, when ten thousand students and faculty members will flood the campus library portal to register books, access digital research archives, and process inter library loans. The university engineering director calls an emergency team briefing: developers are pushing hotfixes late into the night, and we cannot have a human being sitting at a laptop clicking Postman buttons manually at two in the morning. We need an automated robot watchdog that runs our test suite automatically on every code push, generates a visual dashboard for university directors, lets us flip between the Campus QA staging server and the live UAT production cluster with a single dropdown click, and runs scheduled cloud smoke checks. In our final chapter, we build that complete continuous integration pipeline using Newman, Jenkins, GitHub Actions, and Postman Cloud Monitors.',
      image: {
        src: cicdGateImg,
        file: 'src/books/technical/programming/testing/zero-to-agentic-api-testing/editions/edition-01/assets/enterprise-cicd-quality-gate.jpg',
        w: 1408,
        h: 768,
        alt: 'Enterprise operations command center during midnight deployment showing CI CD deployment gate with green pass shields.',
        caption: 'The Midnight Launch Guard: Automated test robots protecting servers during midnight updates.',
        points: [
          'Automated Stop Sign: Blocking broken code immediately so bad updates never reach real students.',
          'Hands Free Testing: Running all test collections automatically in the background without opening the Postman desktop app.',
          'Clear Visual Reports: Creating colorful web dashboards so the engineering team can see test results in one glance.',
        ],
      },
    },
    {
      type: 'heading',
      text: 'Step 1: The Continuous Integration Testing Flow',
    },
    {
      type: 'image',
      layout: 'stacked',
      badge: 'HEADLESS CI CD PIPELINE',
      title: 'Headless CI CD Pipeline: Automated Newman Gating on Every Git Commit',
      text: 'Newman bridges the gap between exploratory testing in the Postman desktop app and automated deployment pipelines. In modern software organizations, automated tests execute headlessly on every git push without human intervention, generating visual HTML Extra dashboards and protecting production clusters.',
      src: newmanImg,
      file: 'src/books/technical/programming/testing/zero-to-agentic-api-testing/editions/edition-01/assets/newman-ci-cd-pipeline.jpg',
      w: 1408,
      h: 768,
      alt: 'CI CD pipeline diagram showing Git commit triggering Jenkins, executing Newman CLI headlessly in Docker, and producing HTML Extra report.',
      caption: 'The complete continuous integration testing pipeline powered by Newman.',
      points: [
        'Step 1 (Code Push): A developer merges new code into the Git repository.',
        'Step 2 (Pipeline Trigger): The CI server (Jenkins or GitHub Actions) detects the commit and spins up a lightweight test container.',
        'Step 3 (Headless Execution): Newman executes the exported Postman collection and environment files without a graphical interface.',
        'Step 4 (Reporting and Gating): Newman generates an interactive HTML Extra report. If all tests pass with exit code 0, deployment proceeds; if any assertion fails, the build is blocked.',
      ],
    },
    {
      type: 'heading',
      text: 'Step 2: Installing Node.js and Newman Globally',
    },
    {
      type: 'paragraph',
      text: 'Newman is built as a command line tool on top of Node.js. Before installing Newman, ensure Node.js is installed on your computer or build server.',
    },
    {
      type: 'steps',
      items: [
        'Download and install Node.js from the official site: https://nodejs.org (select LTS version).',
        'Verify your installation in your terminal by checking the versions: run `node -v` and `npm -v`.',
        'Verify your system path environment variable so Node is accessible globally from any directory (on Mac check `echo $PATH`, on Windows check System Properties > Environment Variables).',
        'Install Newman globally using the Node Package Manager: run `npm install -g newman`.',
      ],
    },
    {
      type: 'heading',
      text: 'Step 3: Exporting Artifacts and The Space in Filename Bug',
    },
    {
      type: 'paragraph',
      text: 'To run our test collection outside the Postman graphical interface, we must export our collection, environment variables, and external data files as portable JSON and CSV artifacts.',
    },
    {
      type: 'steps',
      items: [
        'Export Collection: In Postman, click the three dots beside your collection and select Export to save `Campus_Library_Collection.json`.',
        'Export Environment: In the Environments manager, click the three dots beside your environment and export `Campus_Library_UAT.json` (using flag -e).',
        'Export Globals: In Global Variables, click Export to save `Campus_Globals.json` (using flag -g).',
        'Prepare CSV Data: Place your `books_data.csv` spreadsheet in the same project directory (using flag -d).',
      ],
    },
    {
      type: 'callout',
      variant: 'tip',
      title: 'Fresher Trap to Avoid: Spaces in Exported Filenames',
      paragraphs: [
        'When you export files from Postman, the default filename often contains spaces (such as `Campus Library Suite.postman_collection.json`).',
        'In terminal environments like bash or Windows PowerShell, spaces act as argument separators. The terminal treats `Campus` as one file and `Library` as another, immediately crashing with a file not found error!',
        'Always rename exported files using underscores or clean alphanumeric names before running terminal commands: `Campus_Library_Collection.json`.',
      ],
    },
    {
      type: 'paragraph',
      text: 'With all artifacts in our project folder, we run our complete collection headlessly from the command prompt:',
    },
    {
      type: 'code',
      filename: 'run-newman-cli.sh',
      lines: [
        '# Execute headless collection run with environment, globals, and CSV data',
        'newman run Campus_Library_Collection.json \\',
        '  -e Campus_Library_UAT.json \\',
        '  -g Campus_Globals.json \\',
        '  -d books_data.csv',
      ],
    },
    {
      type: 'terminal',
      command: 'newman run Campus_Library_Collection.json -e Campus_Library_UAT.json -d books_data.csv',
      lines: [
        'Iteration 1 of 3: Processing "Learn Postman Testing"',
        'POST https://uat-api.campuslibrary.org/v1/books [200 OK, 248B, 185ms]',
        '  ✓ Status code is 200 OK',
        '  ✓ Response contains successfully added message',
        '  ✓ Backend generated ID correctly concatenates ISBN and aisle',
        '',
        'GET https://uat-api.campuslibrary.org/v1/books?id=9781227 [200 OK, 192B, 142ms]',
        '  ✓ GetBook response returns an array with at least one record',
        '  ✓ Retrieved book author matches the original creation author',
        '',
        'POST https://uat-api.campuslibrary.org/v1/books/delete [200 OK, 212B, 158ms]',
        '  ✓ Book is successfully deleted message verified',
        '',
        '┌─────────────────────────┬──────────┬──────────┐',
        '│                         │ Executed │   Failed │',
        '├─────────────────────────┼──────────┼──────────┤',
        '│              iterations │        3 │        0 │',
        '│                requests │        9 │        0 │',
        '│            test-scripts │       18 │        0 │',
        '│      prerequest-scripts │       12 │        0 │',
        '│              assertions │       18 │        0 │',
        '└─────────────────────────┴──────────┴──────────┘',
        'Execution Summary: 3 iterations, 9 requests, 18 assertions, 0 failures (518 ms)',
      ],
    },
    {
      type: 'heading',
      text: 'Step 4: Generating Publication Grade HTML Extra Dashboards',
    },
    {
      type: 'paragraph',
      text: 'Terminal output is great for developers, but engineering directors and quality assurance managers need visual dashboards. We install the `newman-reporter-htmlextra` plugin to generate publication grade reports. You can download the complete runner script: [Download HTML Extra Runner Script](/materials/zero-to-agentic-api-testing/lesson-13/install-and-run-htmlextra.sh).',
    },
    {
      type: 'code',
      filename: 'install-and-run-htmlextra.sh',
      lines: [
        '# Install the HTML Extra reporter globally',
        'npm install -g newman-reporter-htmlextra',
        '',
        '# Execute collection and generate interactive dashboard',
        'newman run Campus_Library_Collection.json \\',
        '  -e Campus_Library_UAT.json \\',
        '  -d books_data.csv \\',
        '  -r cli,htmlextra \\',
        '  --reporter-htmlextra-export reports/dashboard.html',
      ],
    },
    {
      type: 'callout',
      variant: 'note',
      title: 'What the HTML Extra Dashboard Delivers',
      paragraphs: [
        '• Summary Visuals: Interactive pie charts and bar graphs showing total requests, passed assertions, and failed checks.',
        '• Granular Request Logs: Expandable cards showing exact request URLs, HTTP methods, wire headers, and request bodies for every iteration.',
        '• Diagnostic Trace: Detailed inspection of response payloads and assertion error diffs for immediate debugging.',
        '• Stakeholder Ready: A single portable HTML file you can email to managers or publish to CI build artifacts.',
      ],
    },
    {
      type: 'heading',
      text: 'Step 5: Setting Up Jenkins and The Working Directory Trap',
    },
    {
      type: 'paragraph',
      text: 'To automate execution without opening a terminal manually, we set up **Jenkins**, the enterprise standard continuous integration server. You can download the Jenkins build script: [Download Jenkins Build Step Script](/materials/zero-to-agentic-api-testing/lesson-13/jenkins-build-step.sh).',
    },
    {
      type: 'steps',
      items: [
        'Download the generic Java package: `jenkins.war` from https://www.jenkins.io.',
        'Start Jenkins from your command prompt on port 9090: `java -jar jenkins.war --httpPort=9090`.',
        'Open your local browser to access the running Jenkins administrative setup dashboard on your assigned port.',
        'Enter the initial administrator password, complete setup, and click New Item to create a Freestyle Project named "Campus Library Regression Pipeline".',
        'In the Build section, click Add build step and select Execute shell (on Linux or Mac) or Execute Windows batch command (on Windows).',
      ],
    },
    {
      type: 'callout',
      variant: 'tip',
      title: 'Fresher Trap to Avoid: The Jenkins Working Directory Trap',
      paragraphs: [
        'When Jenkins runs a job, it executes from its own internal workspace directory (such as `/var/jenkins_home` or your user profile folder), where your exported collection files do not exist.',
        'If you simply paste `newman run Campus_Library_Collection.json`, Jenkins immediately aborts with an error saying the file cannot be found!',
        'How to fix: In your Jenkins build step, always navigate to your project folder first using the cd command before running Newman:',
      ],
    },
    {
      type: 'code',
      filename: 'jenkins-build-step.sh',
      lines: [
        '# Step 1: Navigate to the directory where exported artifacts are stored',
        'cd /home/user/postman_execution',
        '',
        '# Step 2: Run Newman with environment and HTML Extra reporter',
        'newman run Campus_Library_Collection.json \\',
        '  -e Campus_Library_UAT.json \\',
        '  -d books_data.csv \\',
        '  -r cli,htmlextra \\',
        '  --reporter-htmlextra-export reports/build_report.html \\',
        '  --bail',
      ],
    },
    {
      type: 'heading',
      text: 'Step 6: Parameterized Jenkins Builds: Dynamic Environment Switching',
    },
    {
      type: 'paragraph',
      text: 'Here is the ultimate enterprise automation requirement: our QA engineers test on the **QA staging cluster** in the morning, but before the midnight release, they must validate the **UAT production mirror**. We do not want to create duplicate Jenkins jobs or edit shell scripts by hand. We make our Jenkins job dynamic using a **Choice Parameter**.',
    },
    {
      type: 'steps',
      items: [
        'In your Jenkins job configuration, check the box: This project is parameterized.',
        'Click Add Parameter and select Choice Parameter.',
        'Set the Parameter Name to: ENV',
        'In the Choices box, enter two options on separate lines: QA and UAT.',
        'Ensure your exported environment files follow a uniform naming convention: `QA.postman_environment.json` and `UAT.postman_environment.json`.',
      ],
    },
    {
      type: 'paragraph',
      text: 'Now, update the Jenkins build script to reference the parameter dynamically using `${ENV}`. You can download the parameterized script: [Download Parameterized Jenkins Build Script](/materials/zero-to-agentic-api-testing/lesson-13/parameterized-jenkins-build.sh):',
    },
    {
      type: 'code',
      filename: 'parameterized-jenkins-build.sh',
      lines: [
        '# Navigate to project folder',
        'cd /home/user/postman_execution',
        '',
        '# Interpolate the selected Jenkins environment choice dynamically',
        'newman run Campus_Library_Collection.json \\',
        '  -e "${ENV}.postman_environment.json" \\',
        '  -d books_data.csv \\',
        '  -r cli,htmlextra \\',
        '  --reporter-htmlextra-export "reports/${ENV}_report.html" \\',
        '  --bail',
      ],
    },
    {
      type: 'paragraph',
      text: 'When you click **Build with Parameters** in Jenkins, a dropdown appears. Selecting QA runs your entire test suite against `https://qa-api.campuslibrary.org`. Selecting UAT runs against `https://uat-api.campuslibrary.org`. One single automated job services your entire enterprise testing lifecycle!',
    },
    {
      type: 'heading',
      text: 'Step 7: Cloud CI CD Pipeline: GitHub Actions',
    },
    {
      type: 'paragraph',
      text: 'For modern cloud engineering teams that host repositories on GitHub, you can execute this identical pipeline automatically on every git commit without hosting a local Jenkins server. You can download the ready to use GitHub workflow: [Download GitHub Actions Workflow](/materials/zero-to-agentic-api-testing/lesson-13/api-tests-workflow.yml):',
    },
    {
      type: 'code',
      filename: 'api-tests-workflow.yml',
      lines: [
        'name: Campus Library API Regression Pipeline',
        'on: [push, pull_request]',
        '',
        'jobs:',
        '  api-regression:',
        '    runs-on: ubuntu-latest',
        '    steps:',
        '      - name: Checkout Repository Code',
        '        uses: actions/checkout@v4',
        '      - name: Setup Node.js Environment',
        '        uses: actions/setup-node@v4',
        '        with:',
        '          node-version: 20',
        '      - name: Install Newman and HTML Extra Reporter',
        '        run: npm install -g newman newman-reporter-htmlextra',
        '      - name: Execute Headless Test Suite',
        '        run: |',
        '          newman run course-materials/zero-to-agentic-api-testing/Zero-to-Agentic-API-Testing.postman_collection.json \\',
        '            -e course-materials/zero-to-agentic-api-testing/Campus-Library-UAT.postman_environment.json \\',
        '            -d course-materials/zero-to-agentic-api-testing/lesson-08/books_data.csv \\',
        '            -r cli,htmlextra \\',
        '            --reporter-htmlextra-export build/regression_report.html \\',
        '            --bail',
      ],
    },
    {
      type: 'heading',
      text: 'Step 8: Scheduled Cloud Watchdogs: Postman Monitors',
    },
    {
      type: 'paragraph',
      text: 'While Jenkins and GitHub Actions run tests when code changes occur, what if no code was deployed during the night, but an external database server went down? To ensure system health without keeping your laptop awake, Postman provides **Monitors**.',
    },
    {
      type: 'paragraph',
      text: 'A Postman Monitor runs your collection periodically on Postman cloud infrastructure according to a schedule you define:',
    },
    {
      type: 'steps',
      items: [
        '1. In Postman, navigate to the Monitors tab on the left sidebar and click Create a Monitor.',
        '2. Assign a monitor name such as "Campus Library Daily Smoke Check".',
        '3. Select the collection to execute and the target environment (`Campus_Library_UAT`).',
        '4. Set the timer schedule: for example, every weekday at 7:00 AM. Postman cloud servers will execute the collection so results are ready before engineers arrive at 9:00 AM.',
        '5. Configure email alerts: enter team email addresses to receive instant notifications if any assertion fails, with automatic retry on transient network errors.',
        '6. Inspecting History and Restoring Items: If an engineer accidentally deletes a collection, navigate to the workspace Trash to restore it immediately.',
      ],
    },
    {
      type: 'mission-accomplished',
      title: 'Mission 3 Accomplished: Autonomous Production Quality Gate!',
      text: 'Our entire campus library test suite now runs headlessly on every code commit in continuous integration pipelines, and runs scheduled smoke checks in the cloud. Any regression is detected and blocked before reaching students and faculty. You have mastered API testing from first principles to enterprise automation!',
    },
    {
      type: 'heading',
      text: 'Step 9: Review and Practice',
    },
    {
      type: 'guess',
      prompt: 'What exit code does Newman return to the terminal when all assertions in a collection pass successfully?',
      options: [
        'Exit code 1',
        'Exit code 0',
        'Exit code 200',
        'Exit code 255',
      ],
      answerIndex: 1,
      explain: 'In Unix and Windows command environments, an exit code of 0 indicates complete success. Any non zero exit code (such as 1) indicates failure, which signals CI pipelines to mark the build as failed.',
    },
    {
      type: 'quiz',
      items: [
        [
          'Why do CI build servers run tests headlessly rather than opening the Postman desktop window?',
          'CI servers run on minimal Linux servers without screens. A headless command line tool consumes minimal memory, starts in milliseconds, and uses exit codes to control deployment pipelines.',
        ],
        [
          'What is the primary difference between a Jenkins pipeline build and a Postman Monitor?',
          'A Jenkins pipeline typically triggers on event driven actions (such as a git push or pull request merge). A Postman Monitor runs on a recurring time schedule in the cloud (such as daily at 7:00 AM) to verify ongoing system health.',
        ],
      ],
    },
    {
      type: 'takeaways',
      items: [
        'Newman runs Postman collections headlessly from command prompts, Docker containers, and CI servers.',
        'Export collection, environment (-e), global (-g), and CSV data (-d) files into a single project folder without spaces in filenames.',
        'The htmlextra reporter creates publication grade interactive dashboards for stakeholders and QA leads.',
        'In Jenkins, always navigate to your project folder using cd before running Newman commands.',
        'Use Jenkins Choice Parameters to switch target test environments dynamically with a single dropdown selection.',
        'Postman Monitors provide scheduled cloud watchdogs running health checks without requiring local machines.',
      ],
    },
    {
      type: 'victory-milestone',
      badge: '★ FINAL CAPSTONE CONQUERED · CI CD DEFENDER',
      rank: 'CHIEF API AUTOMATION & QUALITY ARCHITECT',
      title: 'Ultimate Enterprise Capstone: Autonomous CI CD Quality Gate Deployed',
      summary: 'You have conquered the entire Zero to Agentic API Testing journey! You took full command of the testing pyramid, automated multi tier campus services, secured microservices with OAuth 2.0, bridged legacy SOAP XML WebServices, and engineered an autonomous continuous integration pipeline powered by Newman, Jenkins, GitHub Actions, and HTML Extra reporting. You stand at the pinnacle of modern software quality engineering.',
      powers: [
        'Orchestrating zero click headless test execution across containerized CI CD pipelines via Newman CLI',
        'Automating strict quality gates with the fail fast bail flag to block breaking commits before deployment',
        'Generating publication grade interactive HTML Extra dashboards with visual charts and granular wire traces',
        'Engineering parameterized Jenkins pipelines with dynamic Choice Parameters for instant QA and UAT switching',
        'Deploying round the clock scheduled cloud watchdogs and automated alerts using Postman Monitors',
      ],
      disastersPrevented: [
        'Averted catastrophic midnight production outages by intercepting breaking backend commits in the pipeline',
        'Eliminated hundreds of hours of manual release signoff delays, enabling true continuous delivery at enterprise scale',
        'Protected live production environments by establishing rigorous automated UAT gating before customer release',
      ],
      warRoomTakeaway: 'You are no longer someone who merely checks if an application works. You are the architect who builds the autonomous shields that guarantee software never fails in production. You command the wire, the contract, the assertion, and the pipeline.',
    },
    {
      type: 'cliffhanger',
      title: 'From Ground Zero to Production Mastery',
      text: 'Congratulations! You have completed all three missions: from auditing the live REST wire and mastering API fundamentals to automating the college library at scale, and hardening enterprise pipelines in CI CD. You are ready to test and automate any API in the world!',
    },
  ],
}
