import chainingImg from '../assets/api-request-chaining-pipeline.jpg'
import arrayPipelineImg from '../assets/javascript-array-pipeline-transform.jpg'

export const lesson07 = {
  id: 'request-chaining',
  icon: '',
  title: 'Request Chaining and Complex Nested JSON Parsing',
  shortTitle: 'Request Chaining and Parsing',
  subtitle: 'Automated property transfer, navigating nested object hierarchies, array methods, and mathematical calculations.',
  tags: ['Chaining', 'Property Transfer', 'Nested JSON', 'Array Methods', 'Calculations'],
  blocks: [
    {
      type: 'mission-hud',
      mission: 'Mission 2: Automating Student and Campus Services at Scale',
      phase: 'Phase 4 of 5: Dynamic Request Chaining & Array Pipelines',
      rank: 'Rank: Automation Pipeline Architect',
      status: 'ACTIVE'
    },
    {
      type: 'chapter-opener',
      achieve: 'Build an autonomous multi request testing pipeline by capturing dynamic IDs, piping them into downstream requests, and verifying nested JSON structures and array mathematics.',
      how: 'Chain AddBook to GetBook and DeleteBook using collection variables, assert exact catalog fields without assuming unreturned properties, and master find, filter, map, and reduce in an advanced audit lab.',
      carry: 'An end to end chained pipeline that creates, validates, and cleans up records autonomously, ready for multi row data driven execution in Chapter 8.'
    },
    {
      type: 'mission-tracker',
      badge: 'MISSION 2 PROGRESS · STEP 4 OF 5',
      title: 'Continuing Mission 2: Assembling the Autonomous Pipeline',
      text: 'Our AddBook request is now parameterized and unique, but we are still manually copying the generated book ID into GetBook and DeleteBook. Our next step in Mission 2 is assembling an autonomous regression pipeline: capturing the response ID automatically, passing it downstream via environment variables, navigating complex nested JSON structures, filtering and mapping arrays, and validating business calculations across multi step transactions.',
    },
    {
      type: 'heading',
      text: 'Step 1: The Three Stage Request Chaining Pipeline',
    },
    {
      type: 'image',
      layout: 'stacked',
      badge: 'REQUEST PIPELINE',
      title: 'Dynamic Request Chaining: Passing Identity Between Dependent Calls',
      text: 'By storing dynamic outputs into variables, a collection can execute dozens of interdependent requests in complete harmony. Subsequent requests consume dynamic keys in their URLs, headers, or request bodies automatically, eliminating all manual copy paste intervention.',
      src: chainingImg,
      file: 'src/books/technical/programming/testing/zero-to-agentic-api-testing/editions/edition-01/assets/api-request-chaining-pipeline.jpg',
      w: 1408,
      h: 768,
      alt: 'Flowchart showing request chaining pipeline: Step 1 AddBook POST creates ID, Step 2 GetBook GET queries ID, Step 3 DeleteBook POST removes ID.',
      caption: 'The autonomous property transfer pipeline across three chained requests.',
      points: [
        'Step 1 (AddBook POST): Dispatches dynamic payload. Tests script extracts generated ID into collection variable book_id.',
        'Step 2 (GetBook GET): Injects {{book_id}} into query params and asserts that the cataloged book name, ISBN, and aisle match the created record.',
        'Step 3 (DeleteBook POST): Reads {{book_id}} in the payload body and asserts that the record is completely removed from the database.',
      ],
    },
    {
      type: 'heading',
      text: 'Step 2: Capturing and Storing the ID in AddBook',
    },
    {
      type: 'paragraph',
      text: 'In the Tests tab of AddBook, parse the response JSON and save the generated ID into a variable so downstream requests can immediately read it. We break this property transfer down into three chunks:',
    },
    {
      type: 'chunked-code',
      badge: 'PROPERTY TRANSFER CHUNKS',
      title: 'Automated Property Transfer Mechanics',
      intro: 'Extracting data from responses and passing downstream:',
      chunks: [
        {
          label: 'Chunk 1: Parsing Incoming Payload',
          filename: 'parse-response.js',
          code: 'const responseData = pm.response.json();',
          title: 'Deserializing JSON Text',
          explanation: 'Converts the raw text into a navigable JavaScript object.',
          keyTakeaway: 'Always deserialize before property lookups.'
        },
        {
          label: 'Chunk 2: Extracting Generated Key',
          filename: 'extract-property.js',
          code: 'const generatedId = responseData.ID;\npm.expect(generatedId, "Generated ID").to.not.be.undefined;',
          title: 'Defensive Property Extraction',
          explanation: 'Validates that the ID key exists and holds a valid string before attempting to save.',
          keyTakeaway: 'Defensive validation prevents saving undefined into variables.'
        },
        {
          label: 'Chunk 3: Persisting to Collection Tier',
          filename: 'persist-variable.js',
          code: 'pm.collectionVariables.set("book_id", generatedId);',
          title: 'Binding to Shared Scope',
          explanation: 'Stores the ID in Collection Scope so subsequent requests can interpolate {{book_id}}.',
          keyTakeaway: 'Collection tier makes variables universally accessible to all folder requests.'
        }
      ]
    },
    {
      type: 'predict-output',
      badge: 'IMAGINE & PREDICT',
      prompt: 'When AddBook completes and GetBook executes with URL: GET /v1/books?id={{book_id}}, what value does Postman send across the network wire?',
      options: [
        'The exact generated ID string (such as "LIB4821") dynamically extracted from the AddBook response',
        'The literal placeholder text "{{book_id}}"',
        'An empty query parameter ?id=',
        'A null pointer exception'
      ],
      answerIndex: 0,
      revealTitle: 'Dynamic Chaining Wire Confirmation',
      explanation: 'Property transfer confirmed! Postman resolves {{book_id}} from Collection Scope, replacing the placeholder with the dynamic ID value (LIB4821) before dispatching the HTTP GET request!'
    },
    {
      type: 'heading',
      text: 'Step 3: Handling JSON Arrays and Validating ID Calculation',
    },
    {
      type: 'paragraph',
      text: 'GetBook returns a JSON array. In JavaScript, access the first record using zero index bracket notation: booksList[0].book_name. Let us validate both the composite ID calculation and the retrieved catalog entry:',
    },
    {
      type: 'code',
      filename: 'validate-id-and-catalog.js',
      lines: [
        '// Step 1: Parse outgoing request payload to verify business calculation',
        'const requestPayload = JSON.parse(pm.request.body.raw);',
        'const expectedCompositeId = requestPayload.isbn + requestPayload.aisle;',
        '',
        '// Step 2: Assert backend ID equals ISBN + aisle in AddBook Tests tab',
        'const responsePayload = pm.response.json();',
        'pm.test("Backend generated ID correctly concatenates ISBN and aisle", function () {',
        '    pm.expect(responsePayload.ID).to.eql(expectedCompositeId);',
        '});',
        '',
        '// Step 3: Assert retrieved catalog entry in GetBook Tests tab',
        'const booksList = pm.response.json();',
        'pm.test("GetBook returns valid array with matching catalog metadata", function () {',
        '    pm.expect(booksList).to.be.an("array").with.lengthOf.atLeast(1);',
        '    pm.expect(booksList[0].book_name).to.eql("Zero to Agentic API Testing");',
        '    pm.expect(booksList[0].isbn).to.eql(pm.collectionVariables.get("ISBN"));',
        '    pm.expect(booksList[0].aisle).to.eql("227");',
        '});',
      ],
    },
    {
      type: 'callout',
      variant: 'note',
      title: 'Contract Precision: Why Author is Omitted from GetBook',
      paragraphs: [
        'Notice that GetBook returns an array containing book_name, isbn, and aisle. The author field supplied during AddBook is not included in this endpoint response.',
        'If you wrote pm.expect(booksList[0].author).to.eql("Alex Mercer"), your test would crash with an undefined failure.',
        'Never assert fields based on wishful thinking: assert strictly against what the API contract promises.',
      ],
    },
    {
      type: 'heading',
      text: 'Step 4: Navigating Complex Nested JSON and Array Methods',
    },
    {
      type: 'paragraph',
      text: 'Real enterprise APIs rarely return flat, simple objects. Instead, responses contain nested hierarchies with multiple layers of parent objects, metadata summaries, and arrays of detailed items. Consider the Campus Library department audit endpoint below. You can download the sample payload: [Download Department Audit Response JSON](/materials/zero-to-agentic-api-testing/lesson-07/department-audit-response.json):',
    },
    {
      type: 'code',
      filename: 'nested-department-response.json',
      lines: [
        '{',
        '  "department": "Computer Science and Systems",',
        '  "budget": {',
        '    "total_allocated": 1500,',
        '    "currency": "USD"',
        '  },',
        '  "books": [',
        '    {',
        '      "id": "BK101",',
        '      "title": "Full Stack API Automation",',
        '      "author": "Dr. Sarah Chen",',
        '      "price": 45,',
        '      "copies": 12,',
        '      "tags": ["api", "testing", "javascript"]',
        '    },',
        '    {',
        '      "id": "BK102",',
        '      "title": "Postman Architecture Patterns",',
        '      "author": "Marcus Vance",',
        '      "price": 55,',
        '      "copies": 8,',
        '      "tags": ["postman", "architecture"]',
        '    },',
        '    {',
        '      "id": "BK103",',
        '      "title": "Distributed Systems Reliability",',
        '      "author": "Elena Rostova",',
        '      "price": 65,',
        '      "copies": 8,',
        '      "tags": ["cloud", "reliability"]',
        '    }',
        '  ]',
        '}',
      ],
    },
    {
      type: 'callout',
      variant: 'note',
      title: 'Four Essential JavaScript Array Methods for API Testers',
      paragraphs: [
        '• find(): Searches an array and returns the very first element matching a boolean condition.',
        '• filter(): Scans the entire array and returns a new array containing all elements that satisfy the condition.',
        '• map(): Transforms every element into a new representation, such as plucking a single property from an object array.',
        '• reduce(): Iterates through an array while accumulating a running total, ideal for verifying mathematical sums.',
      ],
    },
    {
      type: 'image',
      layout: 'stacked',
      badge: 'DATA TRANSFORMATION',
      title: 'JavaScript Array Transformation Pipeline: Filtering, Mapping, and Aggregating',
      text: 'Modern enterprise APIs deliver deep hierarchical payloads. Understanding how find, map, filter, and reduce transform JSON arrays allows automation engineers to locate specific records, compute expected financial aggregates, and assert mathematical integrity across entire catalogs.',
      src: arrayPipelineImg,
      file: 'src/books/technical/programming/testing/zero-to-agentic-api-testing/editions/edition-01/assets/javascript-array-pipeline-transform.jpg',
      w: 1408,
      h: 768,
      alt: 'JavaScript array transformation pipeline showing raw JSON array flowing into filter stage, map transformation stage, and reduce accumulation stage.',
      caption: 'The JavaScript Array Transformation Pipeline: Filtering, mapping, and reducing nested API data.',
      points: [
        'Stage 1 (Raw JSON Array): The incoming API response delivers an array of book objects containing titles and unit prices.',
        'Stage 2 (Filter Stage): books.filter() scans the array and extracts only items matching the condition (books priced above 30 dollars), discarding non matching records.',
        'Stage 3 (Map Stage): filteredBooks.map() transforms each item into a formatted line item object with calculated item totals.',
        'Stage 4 (Reduce Stage): mappedItems.reduce() accumulates each item total into a single running total, producing the final invoice sum of 126.',
      ],
    },
    {
      type: 'heading',
      text: 'Step 5: Writing Advanced Assertions: Finding, Filtering, and Summing',
    },
    {
      type: 'paragraph',
      text: 'Here is how we use these modern JavaScript methods inside Postman test scripts to verify complete schemas, locate target records, and validate mathematical integrity. You can download the script: [Download Advanced Array Assertions Script](/materials/zero-to-agentic-api-testing/lesson-07/advanced-array-assertions.js):',
    },
    {
      type: 'code',
      filename: 'advanced-nested-json-assertions.js',
      lines: [
        'const responseData = pm.response.json();',
        '',
        '// Test 1: Assert top level object and array size',
        'pm.test("Department audit returns valid book records", function () {',
        '    pm.expect(responseData.department).to.eql("Computer Science and Systems");',
        '    pm.expect(responseData.books).to.be.an("array").with.lengthOf(3);',
        '});',
        '',
        '// Test 2: Locate a specific book using find() and assert all keys exist',
        'pm.test("Locate Postman Architecture Patterns and verify its schema", function () {',
        '    const targetBook = responseData.books.find(book => book.title === "Postman Architecture Patterns");',
        '    pm.expect(targetBook, "Target book must exist").to.not.be.undefined;',
        '    pm.expect(targetBook.price).to.eql(55);',
        '    pm.expect(targetBook).to.have.all.keys("id", "title", "author", "price", "copies", "tags");',
        '});',
        '',
        '// Test 3: Extract titles using map() and filter premium books',
        'pm.test("Verify premium collection and extracted titles", function () {',
        '    const titles = responseData.books.map(book => book.title);',
        '    pm.expect(titles).to.include("Full Stack API Automation");',
        '',
        '    const premiumBooks = responseData.books.filter(book => book.price >= 50);',
        '    pm.expect(premiumBooks.length).to.eql(2);',
        '});',
        '',
        '// Test 4: Calculate mathematical sum using reduce()',
        'pm.test("Calculated purchase total matches allocated budget", function () {',
        '    const calculatedTotal = responseData.books.reduce(function (runningSum, book) {',
        '        return runningSum + (book.price * book.copies);',
        '    }, 0);',
        '',
        '    // (45 * 12 = 540) + (55 * 8 = 440) + (65 * 8 = 520) = 1500',
        '    pm.expect(calculatedTotal).to.eql(responseData.budget.total_allocated);',
        '});',
      ],
    },
    {
      type: 'callout',
      variant: 'tip',
      title: 'Fresher Trap to Avoid: Forgetting the Initial Value in reduce()',
      paragraphs: [
        'When using `array.reduce()` to calculate a sum, always provide `0` as the second argument: `reduce(function(...) { ... }, 0);`.',
        'If you omit the `0`, JavaScript sets the initial accumulator to the first object in the array rather than the number zero! Your addition will result in strange string concatenation errors like `[object Object]440520` instead of `1500`.',
        'Always supply `0` as the starting number when accumulating mathematical totals.',
      ],
    },
    {
      type: 'heading',
      text: 'Step 6: The Autonomous Library Lifecycle Pipeline',
    },
    {
      type: 'paragraph',
      text: 'Now let us connect our entire automated library workflow into an unbroken, autonomous sequence in Postman:',
    },
    {
      type: 'steps',
      items: [
        '1. POST AddBook: Dispatches dynamic payload with generated ISBN. Tests script captures the created composite ID: pm.collectionVariables.set("book_id", jsonData.ID).',
        '2. GET GetBook: Calls /v1/books?id={{book_id}}. Tests script confirms that book_name, isbn, and aisle match the created record.',
        '3. POST DeleteBook: Dispatches /v1/books/delete with body {"ID": "{{book_id}}"}. Confirms deletion confirmation from server.',
        '4. Advanced Side Lab (GET DepartmentAudit): Fetches the departmental inventory array and executes reduce() summation to verify fiscal budget totals.',
      ],
    },
    {
      type: 'heading',
      text: 'Step 7: Executing the Suite with Collection Runner',
    },
    {
      type: 'terminal',
      command: 'Postman Collection Runner Execution Summary',
      lines: [
        '1. POST AddBook: 200 OK (180 ms) : 2 of 2 passed (Captured book_id)',
        '2. GET GetBook: 200 OK (145 ms) : 2 of 2 passed (Verified book_id {{book_id}})',
        '3. POST DeleteBook: 200 OK (130 ms) : 1 of 1 passed (Teardown completed)',
        '4. GET DepartmentAudit (Side Lab): 200 OK (185 ms) : 3 of 3 passed (Nested array sum verified)',
        'Collection Run Complete: 4 requests, 8 assertions, 0 failures (640 ms)',
      ],
    },
    {
      type: 'battle-scar',
      metric: 'Order Processing Pipeline Failure',
      title: 'The Silent Null ID Disaster: The Perils of Unchecked Property Transfer',
      context: 'An online ticketing company deployed a microservice update that changed the confirmation key from id to order_id in their reservation endpoint. The downstream payment capture step in the automated test suite continued to look for data.id without defensive validation. The variable was set to undefined, and the payment API was called with: POST /v1/payments/capture?orderId=undefined. Because the payment API did not validate the parameter, thousands of transactions were recorded against a null order ID, requiring emergency database reconciliations.',
      takeaway: 'Always validate that dynamic properties exist before saving them to collection or environment variables. Defensive checks like pm.expect(data.id).to.not.be.undefined prevent corrupted downstream request pipelines.'
    },
    {
      type: 'triage',
      title: 'War Room Triage: The Mystery of the Uncaught TypeError in Array Parsing',
      scenario: 'You are writing an assertion to verify the price of the third book in an audit response: pm.expect(data.department.courses[2].books[0].price).to.eql(45). The test runner throws a fatal error: "TypeError: Cannot read property books of undefined". What is the most likely structural defect in the response?',
      options: [
        'Postman does not support zero based array indexing.',
        'The courses array contained only two elements, so courses[2] resolved to undefined, making .books an invalid property lookup.',
        'The price field in JSON must always be wrapped in quotation marks.',
        'Array methods in JavaScript cannot be executed inside the Tests tab.'
      ],
      answerIndex: 1,
      debrief: 'Zero based index boundary overflow! In JavaScript, array indices start at 0. Therefore, the third item is at index 2. If the courses array contains only two courses (indices 0 and 1), courses[2] evaluates to undefined, and attempting to access .books throws a fatal TypeError. Always assert array length before indexing into nested elements!',
      traps: [
        'JavaScript arrays are universally zero indexed across all engines.',
        '',
        'JSON numbers are valid without quotation marks.',
        'The Postman Tests tab executes full modern JavaScript with complete array method support.'
      ]
    },
    {
      type: 'heading',
      text: 'Step 8: Review and Practice',
    },
    {
      type: 'guess',
      prompt: 'If an API response returns an array of objects called courses, which JavaScript method finds the single course object whose title is "REST Automation"?',
      options: [
        'courses.find(item => item.title === "REST Automation")',
        'courses.get("REST Automation")',
        'courses.locate("REST Automation")',
        'courses.filterOne("REST Automation")',
      ],
      answerIndex: 0,
      explain: 'The find method evaluates each element in an array and returns the first element that satisfies the provided condition.',
    },
    {
      type: 'quiz',
      items: [
        [
          'What is property transfer in API test automation?',
          'Property transfer is capturing dynamic values from an earlier API response and injecting them into downstream request parameters or payloads.',
        ],
        [
          'Why must enterprise regression suites include automated teardown cleanup requests?',
          'Automated tests run continuously in CI CD pipelines. If tests do not delete the orders and products they create, test databases accumulate thousands of orphaned records, causing database bloat and false uniqueness failures.',
        ],
      ],
    },
    {
      type: 'takeaways',
      items: [
        'Request chaining connects isolated API calls into complete automated user journeys.',
        'Use environment variables to transfer identifiers across sequential requests.',
        'Use find to locate objects, filter to subset collections, and map to extract property lists.',
        'Use reduce to compute mathematical sums across nested arrays and assert business logic.',
        'Automated teardown steps clean up created resources, keeping test databases pure and idempotent.',
      ],
    },
    {
      type: 'victory-milestone',
      badge: 'MISSION 2 PHASE 4 CLEARED',
      rank: 'PRINCIPAL API TEST ARCHITECT',
      title: 'Architectural Triumph: Deep Array Pipelines & Request Chaining Mastered',
      summary: 'You linked disconnected HTTP requests into a living, breathing autonomous transaction pipeline. You extracted dynamic IDs, traversed multilevel nested objects without crash errors, performed high speed array transformations (find, filter, map), and mathematically verified financial balance totals using reduce. You operate at the highest echelon of API automation.',
      powers: [
        'Dynamic property transfer: piping tokens, session cookies, and resource IDs across multi request suites',
        'Deep nested JSON parsing: safely traversing multilevel object trees and arrays without null reference exceptions',
        'Functional array pipelines: wielding find, filter, and map to isolate specific records in complex payloads',
        'Mathematical business logic verification: aggregating invoice and catalog totals dynamically using reduce',
        'Zero footprint test execution: deploying automated teardown deletions that leave databases perfectly pristine',
      ],
      disastersPrevented: [
        'Averted silent financial balance discrepancies by verifying computed cart totals against backend invoices',
        'Stopped catastrophic test database pollution where uncleaned test orders exhaust database storage and IDs',
        'Eliminated brittle hardcoded test suites that crash whenever upstream backend developers alter resource IDs',
      ],
      warRoomTakeaway: 'Isolated API checks only test plumbing. Chained request pipelines test real world user journeys and business reality. When your chained suite passes, the entire business flow is guaranteed.',
    },
    {
      type: 'cliffhanger',
      title: 'Continuing Mission 2: Scaling to bulk inventory',
      text: 'Our chained pipeline and nested assertions work cleanly for single and nested requests. But what if a shipment of 100 new books arrives in a CSV spreadsheet? In Chapter 8, we complete Mission 2: driving bulk automated execution using external CSV and JSON data files!',
    },
  ],
}
