import fs from 'node:fs/promises'
import { THEME_TOKENS } from '../src/publishing/design-tokens.js'

const cssName = key => `--${key.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/([a-zA-Z])([0-9])/g, '$1-$2').toLowerCase()}`
const declarations = tokens => Object.entries(tokens).map(([key, value]) => `  ${cssName(key)}: ${value};`).join('\n')
const css = `/* Generated by scripts/generate-styles.mjs from src/publishing/design-tokens.js. */
:root,
[data-theme='light'] {
${declarations(THEME_TOKENS.light)}
}

[data-theme='dark'] {
${declarations(THEME_TOKENS.dark)}
}
`
await fs.mkdir('src/styles/core', { recursive: true })
await fs.writeFile('src/styles/core/tokens.css', css)
console.log('Generated src/styles/core/tokens.css')
