import fs from 'node:fs/promises'
import path from 'node:path'
import { discoverBooks, projectRelative, toPosix } from './lib/book-system.mjs'

const ROOT = process.cwd()
const OUTPUT_DIR = path.join(ROOT, 'src/catalog/generated')
const books = await discoverBooks()
const stateLabel = value => value.split('-').map(word => word[0].toUpperCase() + word.slice(1)).join(' ')

const catalog = books.map(({ manifest, edition, releases }) => ({
  id: manifest.id,
  domain: manifest.domain,
  subdomain: manifest.subdomain,
  profile: manifest.profile,
  title: manifest.title,
  subtitle: manifest.subtitle || '',
  series: manifest.series || '',
  author: manifest.author,
  status: manifest.statusLabel || stateLabel(manifest.status),
  statusTone: manifest.status === 'published' ? 'ready' : manifest.status === 'in-progress' ? 'progress' : manifest.status,
  progress: manifest.progress,
  readable: manifest.readable,
  currentEdition: edition.id,
  editionLabel: edition.label,
  contentVersion: edition.contentVersion,
  verifiedThrough: edition.verifiedThrough,
  releaseCount: releases.length,
  latestRelease: releases.at(-1)?.release?.contentVersion || null,
  route: manifest.route,
  nextMilestone: manifest.nextMilestone || '',
  completedLessons: manifest.chapters.length,
  lessons: manifest.chapters,
  formats: manifest.formats.map(item => ({ label: item.label, state: stateLabel(item.state) })),
  branding: manifest.branding.map(item => ({ label: item.label, state: item.stateLabel })),
}))

const readableBooks = books.filter(({ manifest, contentFile }) => manifest.readable && contentFile)
const registryLines = readableBooks.map(({ manifest, contentFile }) => {
  const fromGenerated = path.relative(OUTPUT_DIR, contentFile)
  const importPath = toPosix(fromGenerated.startsWith('.') ? fromGenerated : `./${fromGenerated}`)
  return `  ${JSON.stringify(manifest.id)}: () => import(${JSON.stringify(importPath)}),`
})

if (!readableBooks.length) throw new Error('At least one readable book is required')
const registry = `// Generated by scripts/generate-catalog.mjs. Do not edit by hand.\nexport const DEFAULT_BOOK_ID = ${JSON.stringify(readableBooks[0].manifest.id)}\nexport const BOOK_LOADERS = {\n${registryLines.join('\n')}\n}\n\nexport async function loadBookPackage(id = DEFAULT_BOOK_ID) {\n  const loader = BOOK_LOADERS[id]\n  if (!loader) throw new Error(\`Unknown book id: \${id}\`)\n  const module = await loader()\n  return { id, lessons: module.default, BOOK: module.BOOK, BRAND: module.BRAND, PREFACE: module.PREFACE }\n}\n`

await fs.mkdir(OUTPUT_DIR, { recursive: true })
await fs.writeFile(path.join(OUTPUT_DIR, 'books.json'), `${JSON.stringify(catalog, null, 2)}\n`)
await fs.writeFile(path.join(OUTPUT_DIR, 'registry.js'), registry)
console.log(`Validated and registered ${books.length} book(s):`)
for (const book of books) console.log(`- ${book.manifest.id} (${book.edition.id} ${book.edition.contentVersion}) from ${projectRelative(book.manifestFile)}`)
